/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.varka.vector;

import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.nio.ByteOrder;

import jdk.incubator.vector.IntVector;
import jdk.incubator.vector.VectorMask;
import jdk.incubator.vector.VectorSpecies;

/**
 * SIMD kernels for the Varka Date/Time MVP: DATE + INTEGER, DATE - INTEGER and DATEDIFF over
 * Arrow buffers (int32 days since epoch + bit-packed validity, bit set = valid).
 *
 * <p>All methods operate on raw addresses (`long`) so that generated bytecode can invoke them via
 * `invokestatic` with a primitive stack (see Task 4). The argument order below is therefore the
 * stack order the bytecode must push.
 *
 * <p>Validity contract: a source validity pointer is dereferenced only when
 * `0 < nullCount < length`; callers with a null-free or all-null source may pass `0L`. The
 * destination validity pointer is always required, and the kernel writes the output null bits.
 * Data values of null output rows are undefined.
 *
 * <p>Int32 arithmetic wraps on overflow, matching Spark's date expressions. Endianness is
 * little-endian (Arrow's in-memory layout). See sql/varka/PLAN_TASK_2.md.
 */
public final class DateVectorOps {

  private static final VectorSpecies<Integer> SPECIES = IntVector.SPECIES_PREFERRED;
  private static final ByteOrder ORDER = ByteOrder.LITTLE_ENDIAN;
  // Arrow validity buffers are not guaranteed 8-byte aligned; unaligned layout skips the
  // alignment check (word offsets stay within bounds thanks to the vector-loop guard, see
  // wordAlignedEnd).
  private static final ValueLayout.OfLong UNALIGNED_LONG = ValueLayout.JAVA_LONG_UNALIGNED;

  private DateVectorOps() {}

  /**
   * The validity bits for the lane group starting at row {@code row}, shifted so that lane 0 is
   * bit 0. {@link VectorMask#fromLong} reads only the lowest {@code SPECIES.length()} bits, so
   * the group's first lane must be moved to bit 0 before the mask is built.
   *
   * <p>The bitmap is addressed one 64-bit word at a time rather than at byte {@code row / 8}: a
   * lane group only starts on a byte boundary when the species is 8 lanes or wider, and a 4-lane
   * species (aarch64 NEON, x86 without AVX2) would otherwise read the bits of an earlier group.
   * Callers must keep {@code row} below {@link #wordAlignedEnd} so the word read is in bounds.
   */
  static long validityBitsAt(MemorySegment validity, long row) {
    return validity.get(UNALIGNED_LONG, (row / 64) * 8L) >>> (row % 64);
  }

  /**
   * ORs {@code laneBits} (lane 0 == row {@code row}) into the bit-packed validity at {@code row},
   * the inverse of {@link #validityBitsAt}. {@code laneBits} holds the mask's lanes in its lowest
   * {@code SPECIES.length()} bits, and {@code row} is a multiple of that width, so the shifted
   * lanes always stay inside one 64-bit word.
   */
  static void orValidityBitsAt(MemorySegment validity, long row, long laneBits) {
    long wordOffset = (row / 64) * 8L;
    validity.set(UNALIGNED_LONG, wordOffset,
        validity.get(UNALIGNED_LONG, wordOffset) | (laneBits << (row % 64)));
  }

  /**
   * The first row NOT covered by a whole 64-bit word of a {@code (length + 7) / 8}-byte validity
   * bitmap. The vector loop stops here because {@link #validityBitsAt} and
   * {@link #orValidityBitsAt} read and write a full 8-byte word; the strict scalar tail, which
   * touches one byte at a time, finishes the rest.
   */
  static long wordAlignedEnd(int length) {
    return ((length + 7) / 8 / 8) * 64L;
  }

  /**
   * dst[i] = src[i] + daysOffset; dst null iff src null.
   *
   * @param srcData address of the source int32 day values.
   * @param srcValidity address of the source bit-packed validity; ignored (may be 0L) when
   *        {@code srcNullCount == 0} or {@code srcNullCount == length}.
   * @param srcNullCount number of null rows in the source.
   * @param dstData address of the destination int32 day values (length * 4 bytes).
   * @param dstValidity address of the destination bit-packed validity
   *        ((length + 7) / 8 bytes); always required.
   * @param length number of rows.
   * @param daysOffset the number of days to add (runtime value, never inlined at codegen).
   */
  public static void vectorAddDays(
      long srcData, long srcValidity, int srcNullCount,
      long dstData, long dstValidity, int length, int daysOffset) {
    if (length <= 0) {
      return;
    }
    MemorySegment src = ofAddress(srcData, length * 4L);
    MemorySegment dst = ofAddress(dstData, length * 4L);
    MemorySegment dstValiditySeg = ofAddress(dstValidity, (length + 7) / 8L);
    zero(dstValiditySeg);
    if (srcNullCount == length) {
      return;  // All-null source: the result is all-null; dst validity is already zeroed.
    }
    boolean hasNulls = srcNullCount > 0;
    MemorySegment validity = hasNulls ? ofAddress(srcValidity, (length + 7) / 8L) : null;
    IntVector offsetVec = IntVector.broadcast(SPECIES, daysOffset);

    long loopBound = SPECIES.loopBound(length);
    long wordEnd = wordAlignedEnd(length);
    long i = 0;
    for (; i < loopBound && i < wordEnd; i += SPECIES.length()) {
      VectorMask<Integer> mask = hasNulls
          ? VectorMask.fromLong(SPECIES, validityBitsAt(validity, i))
          : VectorMask.fromLong(SPECIES, -1L);  // all-true mask
      long byteOffset = i * 4L;
      IntVector va = IntVector.fromMemorySegment(SPECIES, src, byteOffset, ORDER, mask);
      va.add(offsetVec, mask).intoMemorySegment(dst, byteOffset, ORDER, mask);
      orValidityBitsAt(dstValiditySeg, i, mask.toLong());
    }
    for (; i < length; i++) {
      boolean valid = !hasNulls || isBitSet(validity, (int) i);
      if (valid) {
        dst.set(ValueLayout.JAVA_INT, i * 4L,
            src.get(ValueLayout.JAVA_INT, i * 4L) + daysOffset);
        setBit(dstValiditySeg, (int) i);
      }
    }
  }

  /**
   * dst[i] = src[i] - daysOffset; dst null iff src null. Delegates to {@link #vectorAddDays}
   * with the negated offset.
   */
  public static void vectorSubDays(
      long srcData, long srcValidity, int srcNullCount,
      long dstData, long dstValidity, int length, int daysOffset) {
    vectorAddDays(srcData, srcValidity, srcNullCount, dstData, dstValidity, length, -daysOffset);
  }

  /**
   * dst[i] = a[i] - b[i]; dst null iff a or b is null (DATEDIFF).
   *
   * @param dataA address of the first source int32 day values (end date).
   * @param validityA address of the first source validity; ignored (may be 0L) when
   *        {@code nullCountA == 0} or {@code nullCountA == length}.
   * @param nullCountA number of null rows in the first source.
   * @param dataB address of the second source int32 day values (start date).
   * @param validityB address of the second source validity; ignored (may be 0L) when
   *        {@code nullCountB == 0} or {@code nullCountB == length}.
   * @param nullCountB number of null rows in the second source.
   * @param dstData address of the destination int32 day values (length * 4 bytes).
   * @param dstValidity address of the destination bit-packed validity
   *        ((length + 7) / 8 bytes); always required.
   * @param length number of rows.
   */
  public static void vectorDateDiff(
      long dataA, long validityA, int nullCountA,
      long dataB, long validityB, int nullCountB,
      long dstData, long dstValidity, int length) {
    if (length <= 0) {
      return;
    }
    MemorySegment a = ofAddress(dataA, length * 4L);
    MemorySegment b = ofAddress(dataB, length * 4L);
    MemorySegment dst = ofAddress(dstData, length * 4L);
    MemorySegment dstValiditySeg = ofAddress(dstValidity, (length + 7) / 8L);
    zero(dstValiditySeg);
    if (nullCountA == length || nullCountB == length) {
      return;  // All-null on either side: the result is all-null.
    }
    boolean hasNullA = nullCountA > 0;
    boolean hasNullB = nullCountB > 0;
    MemorySegment validityAseg =
        hasNullA ? ofAddress(validityA, (length + 7) / 8L) : null;
    MemorySegment validityBseg =
        hasNullB ? ofAddress(validityB, (length + 7) / 8L) : null;

    long loopBound = SPECIES.loopBound(length);
    long wordEnd = wordAlignedEnd(length);
    long i = 0;
    for (; i < loopBound && i < wordEnd; i += SPECIES.length()) {
      VectorMask<Integer> maskA = hasNullA
          ? VectorMask.fromLong(SPECIES, validityBitsAt(validityAseg, i))
          : VectorMask.fromLong(SPECIES, -1L);  // all-true mask
      VectorMask<Integer> maskB = hasNullB
          ? VectorMask.fromLong(SPECIES, validityBitsAt(validityBseg, i))
          : VectorMask.fromLong(SPECIES, -1L);  // all-true mask
      VectorMask<Integer> mask = maskA.and(maskB);
      long byteOffset = i * 4L;
      IntVector va = IntVector.fromMemorySegment(SPECIES, a, byteOffset, ORDER, mask);
      IntVector vb = IntVector.fromMemorySegment(SPECIES, b, byteOffset, ORDER, mask);
      va.sub(vb, mask).intoMemorySegment(dst, byteOffset, ORDER, mask);
      orValidityBitsAt(dstValiditySeg, i, mask.toLong());
    }
    for (; i < length; i++) {
      boolean validA = !hasNullA || isBitSet(validityAseg, (int) i);
      boolean validB = !hasNullB || isBitSet(validityBseg, (int) i);
      if (validA && validB) {
        dst.set(ValueLayout.JAVA_INT, i * 4L,
            a.get(ValueLayout.JAVA_INT, i * 4L) - b.get(ValueLayout.JAVA_INT, i * 4L));
        setBit(dstValiditySeg, (int) i);
      }
    }
  }

  private static boolean isBitSet(MemorySegment validity, int i) {
    return (validity.get(ValueLayout.JAVA_BYTE, i / 8L) & (1 << (i % 8))) != 0;
  }

  private static void setBit(MemorySegment validity, int i) {
    long off = i / 8L;
    validity.set(ValueLayout.JAVA_BYTE, off,
        (byte) (validity.get(ValueLayout.JAVA_BYTE, off) | (1 << (i % 8))));
  }

  private static void zero(MemorySegment seg) {
    for (long off = 0; off < seg.byteSize(); off++) {
      seg.set(ValueLayout.JAVA_BYTE, off, (byte) 0);
    }
  }

  private static MemorySegment ofAddress(long addr, long bytes) {
    return MemorySegment.ofAddress(addr).reinterpret(bytes);
  }
}
