/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.varka.vector;

import static org.apache.spark.sql.varka.vector.VarkaVectorSupport.isBitSet;
import static org.apache.spark.sql.varka.vector.VarkaVectorSupport.ofAddress;
import static org.apache.spark.sql.varka.vector.VarkaVectorSupport.orValidityBitsAt;
import static org.apache.spark.sql.varka.vector.VarkaVectorSupport.setBit;
import static org.apache.spark.sql.varka.vector.VarkaVectorSupport.validityBitsAt;
import static org.apache.spark.sql.varka.vector.VarkaVectorSupport.zero;

import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.nio.ByteOrder;

import jdk.incubator.vector.IntVector;
import jdk.incubator.vector.VectorMask;
import jdk.incubator.vector.VectorSpecies;

/**
 * SIMD kernels for the Varka Date/Time MVP: DATE + INTEGER, DATE - INTEGER and DATEDIFF over
 * Arrow buffers (int32 days since epoch + bit-packed validity, bit set = valid).
 *
 * <p>All methods operate on raw addresses (`long`) so that generated bytecode can invoke them via
 * `invokestatic` with a primitive stack (see Task 4). The argument order below is therefore the
 * stack order the bytecode must push.
 *
 * <p>Validity contract: a source validity pointer is dereferenced only when
 * `0 < nullCount < length`; callers with a null-free or all-null source may pass `0L`. The
 * destination validity pointer is always required, and the kernel writes the output null bits.
 * Data values of null output rows are undefined.
 *
 * <p>Int32 arithmetic wraps on overflow, matching Spark's date expressions. Endianness is
 * little-endian (Arrow's in-memory layout). See sql/varka/PLAN_TASK_2.md.
 *
 * <h2>The shape of a kernel</h2>
 *
 * <p>These are the reference implementation for the kernels that follow them, so the order of
 * operations below is deliberate rather than incidental. A new kernel should keep it:
 *
 * <ol>
 *   <li><b>Return early on an empty batch.</b> There is nothing to write, and every step below
 *       assumes at least one row.</li>
 *   <li><b>Wrap each address at its nominal size</b> - {@code length * 4} bytes for data,
 *       {@code (length + 7) / 8} for a bitmap - with {@link VarkaVectorSupport#ofAddress}. That
 *       size is the only bounds check a kernel gets, because the caller hands over a bare
 *       {@code long}. Sizing a
 *       segment to whatever the underlying buffer happens to have allocated would turn reads
 *       past the end of the batch into silent successes.</li>
 *   <li><b>Zero the destination validity before any early return</b>, so that every path which
 *       leaves rows unwritten leaves them null. Both loops below only ever OR bits in; nothing
 *       clears one.</li>
 *   <li><b>Take the all-null shortcut</b> for each source whose {@code nullCount == length}: the
 *       result is entirely null and the zeroed destination validity already says so. This is
 *       also what lets a caller pass {@code 0L} for that source's validity address.</li>
 *   <li><b>Build a mask per lane group</b> from the source validity - or an all-true mask when
 *       the source has no nulls - and use it for the loads, the arithmetic and the store alike.
 *       Masked-off lanes are never read, so a null row cannot fault or contribute; with several
 *       sources, AND their masks so a row is valid only where all of them are.</li>
 *   <li><b>Run the vector loop to {@link VectorSpecies#loopBound} and finish with a scalar
 *       tail</b> of fewer than one lane group. The two must agree row for row.
 *       {@code DateVectorOpsTest} checks each kernel against a scalar reference at sizes that
 *       straddle every lane and byte boundary, and {@code DateVectorOpsBitmapTest} walks every
 *       lane width the Vector API admits, including the ones this host cannot produce.</li>
 * </ol>
 *
 * <p>Three things are easy to get wrong and hard to see afterwards. The destination data of a
 * null row is undefined - never assert on it - because the masked store skips those lanes. Every
 * validity access has to be bounded by the lane group rather than by a machine word, or the
 * kernel reads past a short bitmap (see {@link VarkaVectorSupport#validityBitsAt}). And the
 * lane count is a property of the host, not a constant: it is 4 on aarch64 NEON and on x86
 * without AVX2, 8 on
 * AVX2 and 16 on AVX-512, so anything derived from it must be computed, never assumed.
 */
public final class DateVectorOps {

  private static final VectorSpecies<Integer> SPECIES = IntVector.SPECIES_PREFERRED;
  private static final ByteOrder ORDER = ByteOrder.LITTLE_ENDIAN;
  private DateVectorOps() {}

  /**
   * dst[i] = src[i] + daysOffset; dst null iff src null.
   *
   * @param srcData address of the source int32 day values.
   * @param srcValidity address of the source bit-packed validity; ignored (may be 0L) when
   *        {@code srcNullCount == 0} or {@code srcNullCount == length}.
   * @param srcNullCount number of null rows in the source.
   * @param dstData address of the destination int32 day values (length * 4 bytes).
   * @param dstValidity address of the destination bit-packed validity
   *        ((length + 7) / 8 bytes); always required.
   * @param length number of rows.
   * @param daysOffset the number of days to add (runtime value, never inlined at codegen).
   */
  public static void vectorAddDays(
      long srcData, long srcValidity, int srcNullCount,
      long dstData, long dstValidity, int length, int daysOffset) {
    // (1) An empty batch has nothing to write, and everything below assumes at least one row.
    if (length <= 0) {
      return;
    }
    // (2) Nominal sizes only: these bounds are what keep the kernel inside the batch.
    MemorySegment src = ofAddress(srcData, length * 4L);
    MemorySegment dst = ofAddress(dstData, length * 4L);
    MemorySegment dstValiditySeg = ofAddress(dstValidity, (length + 7) / 8L);
    // (3) Zero before any return below, so rows this kernel does not write come out null.
    zero(dstValiditySeg);
    // (4) All-null source: the result is all-null, which the zeroed validity already says.
    if (srcNullCount == length) {
      return;
    }
    // The source validity is mapped only when the source actually has nulls - the branch below
    // never touches it otherwise - which is what lets a null-free caller pass 0L for it.
    boolean hasNulls = srcNullCount > 0;
    MemorySegment validity = hasNulls ? ofAddress(srcValidity, (length + 7) / 8L) : null;
    // The offset is a runtime value broadcast into every lane, never folded in at codegen: one
    // assembled kernel serves every literal a query might use.
    IntVector offsetVec = IntVector.broadcast(SPECIES, daysOffset);

    // (5) and (6): one lane group per iteration, up to the last whole group.
    long loopBound = SPECIES.loopBound(length);
    int lanes = SPECIES.length();
    long i = 0;
    for (; i < loopBound; i += lanes) {
      // The mask drives the load, the add and the store together, so a null lane is never read
      // (it cannot fault on a poisoned value) and never written (its dst data stays undefined).
      VectorMask<Integer> mask = hasNulls
          ? VectorMask.fromLong(SPECIES, validityBitsAt(validity, i, lanes))
          : VectorMask.fromLong(SPECIES, -1L);  // all-true mask
      long byteOffset = i * 4L;
      IntVector va = IntVector.fromMemorySegment(SPECIES, src, byteOffset, ORDER, mask);
      // Lane-wise int add: wraps on overflow, which is what Spark's DateAdd does too.
      va.add(offsetVec, mask).intoMemorySegment(dst, byteOffset, ORDER, mask);
      // The same mask is this group's output validity: dst is null exactly where src was.
      orValidityBitsAt(dstValiditySeg, i, mask.toLong(), lanes);
    }
    // Scalar tail: the fewer than `lanes` rows no whole group covered. It has to agree with the
    // loop above row for row, so it repeats the same three steps one row at a time.
    for (; i < length; i++) {
      boolean valid = !hasNulls || isBitSet(validity, (int) i);
      if (valid) {
        dst.set(ValueLayout.JAVA_INT, i * 4L,
            src.get(ValueLayout.JAVA_INT, i * 4L) + daysOffset);
        setBit(dstValiditySeg, (int) i);
      }
    }
  }

  /**
   * dst[i] = src[i] - daysOffset; dst null iff src null. Delegates to {@link #vectorAddDays}
   * with the negated offset.
   *
   * <p>Subtracting and adding the negation agree for every {@code int}, including
   * {@code Integer.MIN_VALUE}, whose negation is itself: both are the same wrap modulo 2^32, and
   * that is the arithmetic Spark's {@code DateSub} performs as well. {@code VarkaDifferentialSuite}
   * pins the boundary offsets against a scalar oracle.
   */
  public static void vectorSubDays(
      long srcData, long srcValidity, int srcNullCount,
      long dstData, long dstValidity, int length, int daysOffset) {
    vectorAddDays(srcData, srcValidity, srcNullCount, dstData, dstValidity, length, -daysOffset);
  }

  /**
   * dst[i] = a[i] - b[i]; dst null iff a or b is null (DATEDIFF).
   *
   * @param dataA address of the first source int32 day values (end date).
   * @param validityA address of the first source validity; ignored (may be 0L) when
   *        {@code nullCountA == 0} or {@code nullCountA == length}.
   * @param nullCountA number of null rows in the first source.
   * @param dataB address of the second source int32 day values (start date).
   * @param validityB address of the second source validity; ignored (may be 0L) when
   *        {@code nullCountB == 0} or {@code nullCountB == length}.
   * @param nullCountB number of null rows in the second source.
   * @param dstData address of the destination int32 day values (length * 4 bytes).
   * @param dstValidity address of the destination bit-packed validity
   *        ((length + 7) / 8 bytes); always required.
   * @param length number of rows.
   */
  public static void vectorDateDiff(
      long dataA, long validityA, int nullCountA,
      long dataB, long validityB, int nullCountB,
      long dstData, long dstValidity, int length) {
    if (length <= 0) {
      return;
    }
    // The same six steps as vectorAddDays, with one source more. See the class javadoc.
    MemorySegment a = ofAddress(dataA, length * 4L);
    MemorySegment b = ofAddress(dataB, length * 4L);
    MemorySegment dst = ofAddress(dstData, length * 4L);
    MemorySegment dstValiditySeg = ofAddress(dstValidity, (length + 7) / 8L);
    zero(dstValiditySeg);
    // Either side being all-null makes every output row null, so one shortcut covers both.
    if (nullCountA == length || nullCountB == length) {
      return;
    }
    boolean hasNullA = nullCountA > 0;
    boolean hasNullB = nullCountB > 0;
    MemorySegment validityAseg =
        hasNullA ? ofAddress(validityA, (length + 7) / 8L) : null;
    MemorySegment validityBseg =
        hasNullB ? ofAddress(validityB, (length + 7) / 8L) : null;

    long loopBound = SPECIES.loopBound(length);
    int lanes = SPECIES.length();
    long i = 0;
    for (; i < loopBound; i += lanes) {
      VectorMask<Integer> maskA = hasNullA
          ? VectorMask.fromLong(SPECIES, validityBitsAt(validityAseg, i, lanes))
          : VectorMask.fromLong(SPECIES, -1L);  // all-true mask
      VectorMask<Integer> maskB = hasNullB
          ? VectorMask.fromLong(SPECIES, validityBitsAt(validityBseg, i, lanes))
          : VectorMask.fromLong(SPECIES, -1L);  // all-true mask
      // A row survives only where both inputs are valid, so the two masks are ANDed - and the
      // result is again both the store mask and the output validity for this group.
      VectorMask<Integer> mask = maskA.and(maskB);
      long byteOffset = i * 4L;
      IntVector va = IntVector.fromMemorySegment(SPECIES, a, byteOffset, ORDER, mask);
      IntVector vb = IntVector.fromMemorySegment(SPECIES, b, byteOffset, ORDER, mask);
      va.sub(vb, mask).intoMemorySegment(dst, byteOffset, ORDER, mask);
      orValidityBitsAt(dstValiditySeg, i, mask.toLong(), lanes);
    }
    for (; i < length; i++) {
      boolean validA = !hasNullA || isBitSet(validityAseg, (int) i);
      boolean validB = !hasNullB || isBitSet(validityBseg, (int) i);
      if (validA && validB) {
        dst.set(ValueLayout.JAVA_INT, i * 4L,
            a.get(ValueLayout.JAVA_INT, i * 4L) - b.get(ValueLayout.JAVA_INT, i * 4L));
        setBit(dstValiditySeg, (int) i);
      }
    }
  }

}
