/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.varka.vector;

import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;

import jdk.incubator.vector.VectorMask;

/**
 * The building blocks a Varka kernel is made of: address wrapping, bit-packed validity access
 * per whole lane group and per an epilogue's partial one, and the single-row counterparts
 * that scalar reference code and the tests use (no production loop reads a row at a time
 * since task 24 gave both the emitted loops and the kernels masked epilogues). Promoted from
 * {@link DateVectorOps} (Task 9) so that generated fused loops can call them by name, exactly as
 * generated dispatchers call the kernels; the hand-written kernels keep using them and remain the
 * reference for how they compose.
 *
 * <p>Everything here is a static method on a final class: a call site is monomorphic, inlines,
 * and stays out of the generated bytecode, which would triple in size if this bit arithmetic were
 * emitted inline for no gain.
 *
 * <p>The correctness constraint that shaped these helpers (milestone 1, finding 1): every
 * validity access must be bounded by the lane group rather than by a machine word, or a kernel
 * reads past a short bitmap. See {@link #validityBitsAt}.
 */
public final class VarkaVectorSupport {

  // Arrow validity buffers are not guaranteed to be aligned to the width they are read at, so
  // every multi-byte validity access uses an unaligned layout to skip the alignment check.
  private static final ValueLayout.OfShort UNALIGNED_SHORT = ValueLayout.JAVA_SHORT_UNALIGNED;
  private static final ValueLayout.OfInt UNALIGNED_INT = ValueLayout.JAVA_INT_UNALIGNED;
  private static final ValueLayout.OfLong UNALIGNED_LONG = ValueLayout.JAVA_LONG_UNALIGNED;

  private VarkaVectorSupport() {}

  /**
   * The number of bitmap bytes a {@code lanes}-wide group occupies. A group starts on a byte
   * boundary once the species is 8 lanes or wider, so it spans exactly {@code lanes / 8} bytes;
   * a narrower group (4 lanes on aarch64 NEON and on x86 without AVX2, and the 1- and 2-lane
   * widths the Vector API admits) starts mid-byte but still fits inside a single one.
   *
   * <p>A species length is always a power of two, so this is always 1, 2, 4 or 8; the helpers
   * below reject anything else rather than over-reading the bitmap on a width they cannot map.
   */
  public static int groupBytes(int lanes) {
    return Math.max(1, lanes / 8);
  }

  /** A mask of the low {@code lanes} bits. */
  public static long laneMask(int lanes) {
    return lanes >= 64 ? -1L : (1L << lanes) - 1;
  }

  /**
   * The validity bits for the {@code lanes}-wide group starting at row {@code row}, shifted so
   * that lane 0 is bit 0. {@link VectorMask#fromLong} reads only the lowest {@code lanes} bits,
   * so the group's first lane must be moved to bit 0 before the mask is built.
   *
   * <p>Only the {@link #groupBytes} bytes the group itself occupies are read, at byte
   * {@code row / 8} - never a fixed 64-bit word. That is what lets a vector loop run to
   * {@code SPECIES.loopBound(length)} over a nominally sized {@code (length + 7) / 8}-byte
   * bitmap: a group whose rows are all below {@code length} can only touch bytes below
   * {@code (length + 7) / 8}. Addressing a whole word instead would read past the end of the
   * bitmap near it, which is why this used to need a word-alignment bound and left every batch
   * under 57 rows to the scalar path.
   */
  public static long validityBitsAt(MemorySegment validity, long row, int lanes) {
    long byteOffset = row / 8;
    long bits = switch (groupBytes(lanes)) {
      case 1 -> validity.get(ValueLayout.JAVA_BYTE, byteOffset) & 0xFFL;
      case 2 -> validity.get(UNALIGNED_SHORT, byteOffset) & 0xFFFFL;
      case 4 -> validity.get(UNALIGNED_INT, byteOffset) & 0xFFFFFFFFL;
      case 8 -> validity.get(UNALIGNED_LONG, byteOffset);
      default -> throw new IllegalArgumentException("Unsupported lane width " + lanes);
    };
    // Zero for every width of 8 lanes or more, where the group is already byte-aligned.
    return bits >>> (row % 8);
  }

  /**
   * ORs {@code laneBits} (lane 0 == row {@code row}) into the bit-packed validity at {@code row},
   * the inverse of {@link #validityBitsAt}. Only the lowest {@code lanes} bits are used, and only
   * the bytes that group occupies are touched, so ORing every group of a bitmap in turn sets
   * exactly the rows those groups cover.
   */
  public static void orValidityBitsAt(MemorySegment validity, long row, long laneBits, int lanes) {
    long byteOffset = row / 8;
    long bits = (laneBits & laneMask(lanes)) << (row % 8);
    switch (groupBytes(lanes)) {
      case 1 -> validity.set(ValueLayout.JAVA_BYTE, byteOffset,
          (byte) (validity.get(ValueLayout.JAVA_BYTE, byteOffset) | bits));
      case 2 -> validity.set(UNALIGNED_SHORT, byteOffset,
          (short) (validity.get(UNALIGNED_SHORT, byteOffset) | bits));
      case 4 -> validity.set(UNALIGNED_INT, byteOffset,
          (int) (validity.get(UNALIGNED_INT, byteOffset) | bits));
      case 8 -> validity.set(UNALIGNED_LONG, byteOffset,
          validity.get(UNALIGNED_LONG, byteOffset) | bits);
      default -> throw new IllegalArgumentException("Unsupported lane width " + lanes);
    }
  }

  // ---------------------------------------------------------------------------------------
  // Width-specialised whole-group access (task 46).
  //
  // The two helpers above take the lane count as an argument, so each carries a four-arm
  // switch on `groupBytes(lanes)` that a caller cannot fold: 153 and 212 bytecode bytes, and
  // C2 refuses to inline the writer inside a fused loop - `NodeCountInliningCutoff` on one
  // compilation and `callee is too large` on another, with `-XX:CompileCommand=inline`
  // changing the reason and not the outcome (task 32, SKILLS.md). Measured through task 45's
  // A/B, one refused call costs 1.87 to 3.24 ns per lane group whatever the vector width,
  // which is why a 4-lane group pays four times per row what a 16-lane group does.
  //
  // The emitter knows the lane count when it writes the bytes, so it can name it: one method
  // per width, with the switch resolved, the lane mask folded into the narrowing cast where
  // the width is a whole number of bytes, and no shift at all where a group starts on a byte
  // boundary. A whole group's first row is a multiple of the lane count, so widths of 8 and
  // above are always byte-aligned and widths below it never span two bytes.
  //
  // Each of these must stay small enough to inline whether or not the call site is judged
  // hot; VarkaVectorSupportWidthTest holds them to the JVM's own MaxInlineSize and to the
  // generic helpers' answers, so the pair can never drift apart silently.
  // ---------------------------------------------------------------------------------------

  /** {@link #validityBitsAt} at 16 lanes: two bytes, byte-aligned, no shift. */
  public static long validityBitsAt16(MemorySegment validity, long row) {
    return validity.get(UNALIGNED_SHORT, row >>> 3) & 0xFFFFL;
  }

  /** {@link #validityBitsAt} at 8 lanes: one byte, byte-aligned, no shift. */
  public static long validityBitsAt8(MemorySegment validity, long row) {
    return validity.get(ValueLayout.JAVA_BYTE, row >>> 3) & 0xFFL;
  }

  /**
   * {@link #validityBitsAt} at 4 lanes: one byte, and the group starts at bit 0 or bit 4 of
   * it. As in the general form, the bits above the group's own are left in place - the caller
   * is {@link VectorMask#fromLong}, which reads only the lowest {@code lanes} of them.
   */
  public static long validityBitsAt4(MemorySegment validity, long row) {
    return (validity.get(ValueLayout.JAVA_BYTE, row >>> 3) & 0xFFL) >>> (row & 7);
  }

  /** {@link #validityBitsAt} at 2 lanes; the 4-lane form's argument, on quarter-byte groups. */
  public static long validityBitsAt2(MemorySegment validity, long row) {
    return (validity.get(ValueLayout.JAVA_BYTE, row >>> 3) & 0xFFL) >>> (row & 7);
  }

  /**
   * {@link #orValidityBitsAt} at 16 lanes. The narrowing cast is the lane mask: it keeps the
   * low sixteen bits of the OR and drops whatever the caller left above them.
   */
  public static void orValidityBitsAt16(MemorySegment validity, long row, long laneBits) {
    long off = row >>> 3;
    validity.set(UNALIGNED_SHORT, off, (short) (validity.get(UNALIGNED_SHORT, off) | laneBits));
  }

  /** {@link #orValidityBitsAt} at 8 lanes; the cast to {@code byte} is the lane mask. */
  public static void orValidityBitsAt8(MemorySegment validity, long row, long laneBits) {
    long off = row >>> 3;
    validity.set(ValueLayout.JAVA_BYTE, off,
        (byte) (validity.get(ValueLayout.JAVA_BYTE, off) | laneBits));
  }

  /**
   * {@link #orValidityBitsAt} at 4 lanes: the group is half a byte, so the bits are masked to
   * four and shifted to the group's own nibble before the OR. Only that one byte is touched.
   */
  public static void orValidityBitsAt4(MemorySegment validity, long row, long laneBits) {
    long off = row >>> 3;
    long bits = (laneBits & 0xFL) << (row & 7);
    validity.set(ValueLayout.JAVA_BYTE, off,
        (byte) (validity.get(ValueLayout.JAVA_BYTE, off) | bits));
  }

  /** {@link #orValidityBitsAt} at 2 lanes; the 4-lane form on quarter-byte groups. */
  public static void orValidityBitsAt2(MemorySegment validity, long row, long laneBits) {
    long off = row >>> 3;
    long bits = (laneBits & 0x3L) << (row & 7);
    validity.set(ValueLayout.JAVA_BYTE, off,
        (byte) (validity.get(ValueLayout.JAVA_BYTE, off) | bits));
  }

  /**
   * {@link #validityBitsAt} for the last, <i>partial</i> lane group: {@code rows} rows starting
   * at {@code row}, where {@code rows} is anything from 1 to {@code lanes - 1} and therefore
   * not a width the byte-span switch above can serve. That switch exists because a whole group
   * spans exactly {@code groupBytes(lanes)} bytes and can be read in one access; a partial
   * group spans {@code (row % 8 + rows + 7) / 8} bytes, which is 1, 2 or 3 and is not a layout
   * size. So this walks those bytes instead - once per batch, on the cold path, where a byte
   * loop costs nothing that matters.
   *
   * <p>Passing {@code rows} to {@link #validityBitsAt} instead is the bug this method exists to
   * prevent, and it is silent: {@code groupBytes(9)} is 1, so a nine-row group would read one
   * byte and report its ninth row null (task 24 hit exactly that).
   */
  public static long partialValidityBitsAt(MemorySegment validity, long row, int rows) {
    long byteOffset = row / 8;
    int shift = (int) (row % 8);
    int spanned = (shift + rows + 7) / 8;
    long bits = 0L;
    for (int b = 0; b < spanned; b++) {
      bits |= (validity.get(ValueLayout.JAVA_BYTE, byteOffset + b) & 0xFFL) << (b * 8);
    }
    return (bits >>> shift) & laneMask(rows);
  }

  /**
   * {@link #orValidityBitsAt} for the last, partial lane group; the inverse of
   * {@link #partialValidityBitsAt} and bounded the same way. Only the {@code rows} lowest bits
   * of {@code laneBits} are used and only the bytes those rows occupy are touched, so a
   * partial group at the end of a nominally sized bitmap cannot write past it - which a
   * whole-group write at the same row would do (row 16 of a 17-row bitmap is three bytes long,
   * and a 16-lane group there would store a short across bytes 2 and 3).
   */
  public static void orPartialValidityBitsAt(
      MemorySegment validity, long row, long laneBits, int rows) {
    long byteOffset = row / 8;
    int shift = (int) (row % 8);
    long bits = (laneBits & laneMask(rows)) << shift;
    int spanned = (shift + rows + 7) / 8;
    for (int b = 0; b < spanned; b++) {
      long off = byteOffset + b;
      byte add = (byte) (bits >>> (b * 8));
      validity.set(ValueLayout.JAVA_BYTE, off,
          (byte) (validity.get(ValueLayout.JAVA_BYTE, off) | add));
    }
  }

  /**
   * Whether row {@code i} is valid. The single-row counterpart to {@link #validityBitsAt}:
   * one row, so one byte, and no lane-width arithmetic to get right.
   */
  public static boolean isBitSet(MemorySegment validity, int i) {
    return (validity.get(ValueLayout.JAVA_BYTE, i / 8L) & (1 << (i % 8))) != 0;
  }

  /**
   * Marks row {@code i} valid. The scalar tail's counterpart to {@link #orValidityBitsAt}, and
   * likewise an OR: it can only add validity, never clear a bit a previous row set in this byte.
   */
  public static void setBit(MemorySegment validity, int i) {
    long off = i / 8L;
    validity.set(ValueLayout.JAVA_BYTE, off,
        (byte) (validity.get(ValueLayout.JAVA_BYTE, off) | (1 << (i % 8))));
  }

  /**
   * Clears a destination validity bitmap. Every kernel calls this before writing anything,
   * because the loops only OR bits in: a row nobody writes has to already read as null.
   */
  public static void zero(MemorySegment seg) {
    seg.fill((byte) 0);
  }

  /**
   * Sets exactly the low {@code rows} bits of a destination validity bitmap and nothing past
   * them: whole {@code 0xFF} bytes for {@code rows / 8}, then the low {@code rows % 8} bits of
   * the byte after those.
   *
   * <p>Task 45's counterpart to {@link #zero}. On a dense batch the dispatcher has already
   * proven every referenced input null-free, and task 11's invariant - every node maps valid
   * inputs to valid outputs, and there is no null-literal node - makes every value output valid
   * on every row. So the bits are known before the loop starts, and the loop's per-lane-group
   * {@code orValidityBitsAt} call is ORing a word of all ones into a bitmap the driver zeroed a
   * moment earlier.
   *
   * <p><b>Exactly {@code rows} bits, not the whole last byte.</b> Today's dense path zeroes
   * {@code (rows + 7) / 8} bytes and then ORs lane-masked words, so the bits past {@code rows}
   * in the final byte are left zero. {@code VarkaLoopEmitterSuite}'s {@code assertSameOutput}
   * compares dense and masked validity byte for byte, and while Arrow's {@code getNullCount}
   * stops at {@code valueCount}, nothing promises every reader does. Producing bit-identical
   * output to the loop is the contract here, and it is what lets the existing differential be
   * this change's oracle rather than something to rewrite.
   */
  public static void setValid(MemorySegment seg, int rows) {
    int wholeBytes = rows >>> 3;
    if (wholeBytes > 0) {
      seg.asSlice(0L, wholeBytes).fill((byte) 0xFF);
    }
    int tail = rows & 7;
    if (tail != 0) {
      seg.set(ValueLayout.JAVA_BYTE, wholeBytes, (byte) ((1 << tail) - 1));
    }
  }

  /**
   * Maps a raw address as a segment of exactly {@code bytes} bytes. The size is the whole point:
   * the caller passes a bare {@code long}, so this is where a kernel says how far it is entitled
   * to read, and the {@link MemorySegment} bounds check enforces it from there on.
   */
  public static MemorySegment ofAddress(long addr, long bytes) {
    return MemorySegment.ofAddress(addr).reinterpret(bytes);
  }
}
