/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.varka.vector;

import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;

import jdk.incubator.vector.VectorMask;

/**
 * The building blocks a Varka kernel is made of: address wrapping, bit-packed validity access
 * per whole lane group and per an epilogue's partial one, and the single-row counterparts
 * that scalar reference code and the tests use (no production loop reads a row at a time
 * gave both the emitted loops and the kernels masked epilogues). Promoted from
 * {@link DateVectorOps} so that generated fused loops can call them by name, exactly as
 * generated dispatchers call the kernels; the hand-written kernels keep using them and remain the
 * reference for how they compose.
 *
 * <p>Everything here is a static method on a final class: a call site is monomorphic, inlines,
 * and stays out of the generated bytecode, which would triple in size if this bit arithmetic were
 * emitted inline for no gain.
 *
 * <p>The correctness constraint that shaped these helpers (milestone 1, finding 1): every
 * validity access must be bounded by the lane group rather than by a machine word, or a kernel
 * reads past a short bitmap. See {@link #validityBitsAt}.
 */
public final class VarkaVectorSupport {

  // Arrow validity buffers are not guaranteed to be aligned to the width they are read at, so
  // every multi-byte validity access uses an unaligned layout to skip the alignment check.
  private static final ValueLayout.OfShort UNALIGNED_SHORT = ValueLayout.JAVA_SHORT_UNALIGNED;
  private static final ValueLayout.OfInt UNALIGNED_INT = ValueLayout.JAVA_INT_UNALIGNED;
  private static final ValueLayout.OfLong UNALIGNED_LONG = ValueLayout.JAVA_LONG_UNALIGNED;

  private VarkaVectorSupport() {}

  /**
   * The number of bitmap bytes a {@code lanes}-wide group occupies. A group starts on a byte
   * boundary once the species is 8 lanes or wider, so it spans exactly {@code lanes / 8} bytes;
   * a narrower group (4 lanes on aarch64 NEON and on x86 without AVX2, and the 1- and 2-lane
   * widths the Vector API admits) starts mid-byte but still fits inside a single one.
   *
   * <p>A species length is always a power of two, so this is always 1, 2, 4 or 8; the helpers
   * below reject anything else rather than over-reading the bitmap on a width they cannot map.
   */
  public static int groupBytes(int lanes) {
    return Math.max(1, lanes / 8);
  }

  /** A mask of the low {@code lanes} bits. */
  public static long laneMask(int lanes) {
    return lanes >= 64 ? -1L : (1L << lanes) - 1;
  }

  /**
   * The validity bits for the {@code lanes}-wide group starting at row {@code row}, shifted so
   * that lane 0 is bit 0. {@link VectorMask#fromLong} reads only the lowest {@code lanes} bits,
   * so the group's first lane must be moved to bit 0 before the mask is built.
   *
   * <p>Only the {@link #groupBytes} bytes the group itself occupies are read, at byte
   * {@code row / 8} - never a fixed 64-bit word. That is what lets a vector loop run to
   * {@code SPECIES.loopBound(length)} over a nominally sized {@code (length + 7) / 8}-byte
   * bitmap: a group whose rows are all below {@code length} can only touch bytes below
   * {@code (length + 7) / 8}. Addressing a whole word instead would read past the end of the
   * bitmap near it, which is why this used to need a word-alignment bound and left every batch
   * under 57 rows to the scalar path.
   */
  public static long validityBitsAt(MemorySegment validity, long row, int lanes) {
    long byteOffset = row / 8;
    long bits = switch (groupBytes(lanes)) {
      case 1 -> validity.get(ValueLayout.JAVA_BYTE, byteOffset) & 0xFFL;
      case 2 -> validity.get(UNALIGNED_SHORT, byteOffset) & 0xFFFFL;
      case 4 -> validity.get(UNALIGNED_INT, byteOffset) & 0xFFFFFFFFL;
      case 8 -> validity.get(UNALIGNED_LONG, byteOffset);
      default -> throw new IllegalArgumentException("Unsupported lane width " + lanes);
    };
    // Zero for every width of 8 lanes or more, where the group is already byte-aligned.
    return bits >>> (row % 8);
  }

  /**
   * ORs {@code laneBits} (lane 0 == row {@code row}) into the bit-packed validity at {@code row},
   * the inverse of {@link #validityBitsAt}. Only the lowest {@code lanes} bits are used, and only
   * the bytes that group occupies are touched, so ORing every group of a bitmap in turn sets
   * exactly the rows those groups cover.
   */
  public static void orValidityBitsAt(MemorySegment validity, long row, long laneBits, int lanes) {
    long byteOffset = row / 8;
    long bits = (laneBits & laneMask(lanes)) << (row % 8);
    switch (groupBytes(lanes)) {
      case 1 -> validity.set(ValueLayout.JAVA_BYTE, byteOffset,
          (byte) (validity.get(ValueLayout.JAVA_BYTE, byteOffset) | bits));
      case 2 -> validity.set(UNALIGNED_SHORT, byteOffset,
          (short) (validity.get(UNALIGNED_SHORT, byteOffset) | bits));
      case 4 -> validity.set(UNALIGNED_INT, byteOffset,
          (int) (validity.get(UNALIGNED_INT, byteOffset) | bits));
      case 8 -> validity.set(UNALIGNED_LONG, byteOffset,
          validity.get(UNALIGNED_LONG, byteOffset) | bits);
      default -> throw new IllegalArgumentException("Unsupported lane width " + lanes);
    }
  }

  // ---------------------------------------------------------------------------------------
  // Width-specialised whole-group access.
  //
  // The two helpers above take the lane count as an argument, so each carries a four-arm
  // switch on `groupBytes(lanes)` that a caller cannot fold: 153 and 212 bytecode bytes, and
  // C2 refuses to inline the writer inside a fused loop - `NodeCountInliningCutoff` on one
  // compilation and `callee is too large` on another, with `-XX:CompileCommand=inline`
  // changing the reason and not the outcome (see SKILLS.md). One refused call // costs 1.87 to 3.24
  // ns per lane group whatever the vector width,
  // which is why a 4-lane group pays four times per row what a 16-lane group does.
  //
  // The emitter knows the lane count when it writes the bytes, so it can name it: one method
  // per width, with the switch resolved, the lane mask folded into the narrowing cast where
  // the width is a whole number of bytes, and no shift at all where a group starts on a byte
  // boundary. A whole group's first row is a multiple of the lane count, so widths of 8 and
  // above are always byte-aligned and widths below it never span two bytes.
  //
  // Each of these must stay small enough to inline whether or not the call site is judged
  // hot; VarkaVectorSupportWidthTest holds them to the JVM's own MaxInlineSize and to the
  // generic helpers' answers, so the pair can never drift apart silently.
  // ---------------------------------------------------------------------------------------

  /** {@link #validityBitsAt} at 16 lanes: two bytes, byte-aligned, no shift. */
  public static long validityBitsAt16(MemorySegment validity, long row) {
    return validity.get(UNALIGNED_SHORT, row >>> 3) & 0xFFFFL;
  }

  /** {@link #validityBitsAt} at 8 lanes: one byte, byte-aligned, no shift. */
  public static long validityBitsAt8(MemorySegment validity, long row) {
    return validity.get(ValueLayout.JAVA_BYTE, row >>> 3) & 0xFFL;
  }

  /**
   * {@link #validityBitsAt} at 4 lanes: one byte, and the group starts at bit 0 or bit 4 of
   * it. As in the general form, the bits above the group's own are left in place - the caller
   * is {@link VectorMask#fromLong}, which reads only the lowest {@code lanes} of them.
   */
  public static long validityBitsAt4(MemorySegment validity, long row) {
    return (validity.get(ValueLayout.JAVA_BYTE, row >>> 3) & 0xFFL) >>> (row & 7);
  }

  /** {@link #validityBitsAt} at 2 lanes; the 4-lane form's argument, on quarter-byte groups. */
  public static long validityBitsAt2(MemorySegment validity, long row) {
    return (validity.get(ValueLayout.JAVA_BYTE, row >>> 3) & 0xFFL) >>> (row & 7);
  }

  /**
   * {@link #orValidityBitsAt} at 16 lanes. The narrowing cast is the lane mask: it keeps the
   * low sixteen bits of the OR and drops whatever the caller left above them.
   */
  public static void orValidityBitsAt16(MemorySegment validity, long row, long laneBits) {
    long off = row >>> 3;
    validity.set(UNALIGNED_SHORT, off, (short) (validity.get(UNALIGNED_SHORT, off) | laneBits));
  }

  /** {@link #orValidityBitsAt} at 8 lanes; the cast to {@code byte} is the lane mask. */
  public static void orValidityBitsAt8(MemorySegment validity, long row, long laneBits) {
    long off = row >>> 3;
    validity.set(ValueLayout.JAVA_BYTE, off,
        (byte) (validity.get(ValueLayout.JAVA_BYTE, off) | laneBits));
  }

  /**
   * {@link #orValidityBitsAt} at 4 lanes: the group is half a byte, so the bits are masked to
   * four and shifted to the group's own nibble before the OR. Only that one byte is touched.
   */
  public static void orValidityBitsAt4(MemorySegment validity, long row, long laneBits) {
    long off = row >>> 3;
    long bits = (laneBits & 0xFL) << (row & 7);
    validity.set(ValueLayout.JAVA_BYTE, off,
        (byte) (validity.get(ValueLayout.JAVA_BYTE, off) | bits));
  }

  /** {@link #orValidityBitsAt} at 2 lanes; the 4-lane form on quarter-byte groups. */
  public static void orValidityBitsAt2(MemorySegment validity, long row, long laneBits) {
    long off = row >>> 3;
    long bits = (laneBits & 0x3L) << (row & 7);
    validity.set(ValueLayout.JAVA_BYTE, off,
        (byte) (validity.get(ValueLayout.JAVA_BYTE, off) | bits));
  }

  /**
   * Stores a whole 64-bit word of destination validity: bit {@code b} of {@code word} is row
   * {@code (row & ~63L) + b}. The whole-word write, and deliberately the one access in this class
   * that addresses a fixed word rather than the bytes a lane group occupies.
   *
   * <p>Two things make that sound here and nowhere else. It is a <i>destination</i> bitmap,
   * which the evaluator allocates: {@code VarkaKernelEvaluatorSuite}'s "a destination validity
   * buffer carries whole 64-bit words, at every length" pins that Arrow gives back at least
   * {@code ((len + 63) / 64) * 8} bytes for every length and every vector class Varka writes,
   * and the emitter sizes the segment to match. And it is a plain store, not an OR, which is
   * sound because the driver has zeroed exactly the outputs that reach it and
   * {@code groupOutputs} gives each output one writing method. A <i>source</i> bitmap has
   * neither property - its sizing belongs to the input batch - which is why
   * {@link #validityBitsAt} still reads a group's own bytes and says so at length.
   *
   * <p>What this buys is the removal of the read. {@code orValidityBitsAt*} loads the group's
   * bytes, ORs and stores them back; at four lanes a group is half a byte, so two consecutive
   * groups read-modify-write the same byte and serialise on it. The caller accumulates a word's
   * groups in a register and calls this once, so the chain is gone rather than tuned around -
   * see {@code PLAN_TASK_76.md} 10.6, which measured the regime.
   */
  public static void putValidityWord(MemorySegment validity, long row, long word) {
    validity.set(UNALIGNED_LONG, (row >>> 6) << 3, word);
  }

  /**
   * {@link #validityBitsAt} for the last, <i>partial</i> lane group: {@code rows} rows starting
   * at {@code row}, where {@code rows} is anything from 1 to {@code lanes - 1} and therefore
   * not a width the byte-span switch above can serve. That switch exists because a whole group
   * spans exactly {@code groupBytes(lanes)} bytes and can be read in one access; a partial
   * group spans {@code (row % 8 + rows + 7) / 8} bytes, which is 1, 2 or 3 and is not a layout
   * size. So this walks those bytes instead - once per batch, on the cold path, where a byte
   * loop costs nothing that matters.
   *
   * <p>Passing {@code rows} to {@link #validityBitsAt} instead is the bug this method exists to
   * prevent, and it is silent: {@code groupBytes(9)} is 1, so a nine-row group would read one byte
   * and report its ninth row null.
   */
  public static long partialValidityBitsAt(MemorySegment validity, long row, int rows) {
    long byteOffset = row / 8;
    int shift = (int) (row % 8);
    int spanned = (shift + rows + 7) / 8;
    long bits = 0L;
    for (int b = 0; b < spanned; b++) {
      bits |= (validity.get(ValueLayout.JAVA_BYTE, byteOffset + b) & 0xFFL) << (b * 8);
    }
    return (bits >>> shift) & laneMask(rows);
  }

  /**
   * {@link #orValidityBitsAt} for the last, partial lane group; the inverse of
   * {@link #partialValidityBitsAt} and bounded the same way. Only the {@code rows} lowest bits
   * of {@code laneBits} are used and only the bytes those rows occupy are touched, so a
   * partial group at the end of a nominally sized bitmap cannot write past it - which a
   * whole-group write at the same row would do (row 16 of a 17-row bitmap is three bytes long,
   * and a 16-lane group there would store a short across bytes 2 and 3).
   */
  public static void orPartialValidityBitsAt(
      MemorySegment validity, long row, long laneBits, int rows) {
    long byteOffset = row / 8;
    int shift = (int) (row % 8);
    long bits = (laneBits & laneMask(rows)) << shift;
    int spanned = (shift + rows + 7) / 8;
    for (int b = 0; b < spanned; b++) {
      long off = byteOffset + b;
      byte add = (byte) (bits >>> (b * 8));
      validity.set(ValueLayout.JAVA_BYTE, off,
          (byte) (validity.get(ValueLayout.JAVA_BYTE, off) | add));
    }
  }

  /**
   * Whether row {@code i} is valid. The single-row counterpart to {@link #validityBitsAt}:
   * one row, so one byte, and no lane-width arithmetic to get right.
   */
  public static boolean isBitSet(MemorySegment validity, int i) {
    return (validity.get(ValueLayout.JAVA_BYTE, i / 8L) & (1 << (i % 8))) != 0;
  }

  /**
   * Marks row {@code i} valid. The scalar tail's counterpart to {@link #orValidityBitsAt}, and
   * likewise an OR: it can only add validity, never clear a bit a previous row set in this byte.
   */
  public static void setBit(MemorySegment validity, int i) {
    long off = i / 8L;
    validity.set(ValueLayout.JAVA_BYTE, off,
        (byte) (validity.get(ValueLayout.JAVA_BYTE, off) | (1 << (i % 8))));
  }

  /**
   * Clears a destination validity bitmap. Every kernel calls this before writing anything,
   * because the loops only OR bits in: a row nobody writes has to already read as null.
   */
  public static void zero(MemorySegment seg) {
    seg.fill((byte) 0);
  }

  /**
   * Sets exactly the low {@code rows} bits of a destination validity bitmap and nothing past
   * them: whole {@code 0xFF} bytes for {@code rows / 8}, then the low {@code rows % 8} bits of
   * the byte after those.
   *
   * <p>The counterpart to {@link #zero}. On a dense batch the dispatcher has already
   * proven every referenced input null-free, and the dense invariant - every node maps valid inputs
   * to valid outputs, and there is no null-literal node - makes every value output valid
   * on every row. So the bits are known before the loop starts, and the loop's per-lane-group
   * {@code orValidityBitsAt} call is ORing a word of all ones into a bitmap the driver zeroed a
   * moment earlier.
   *
   * <p><b>Exactly {@code rows} bits, not the whole last byte.</b> Today's dense path zeroes
   * {@code (rows + 7) / 8} bytes and then ORs lane-masked words, so the bits past {@code rows}
   * in the final byte are left zero. {@code VarkaEmitterTestBase}'s {@code assertSameOutput}
   * compares dense and masked validity byte for byte, and while Arrow's {@code getNullCount}
   * stops at {@code valueCount}, nothing promises every reader does. Producing bit-identical
   * output to the loop is the contract here, and it is what lets the existing differential be
   * this change's oracle rather than something to rewrite.
   */
  public static void setValid(MemorySegment seg, int rows) {
    int wholeBytes = rows >>> 3;
    if (wholeBytes > 0) {
      seg.asSlice(0L, wholeBytes).fill((byte) 0xFF);
    }
    int tail = rows & 7;
    if (tail != 0) {
      seg.set(ValueLayout.JAVA_BYTE, wholeBytes, (byte) ((1 << tail) - 1));
    }
  }

  /**
   * {@code dst = src} over exactly the low {@code rows} bits, and zero past them in the final
   * byte - the single-input case of the whole-batch bitmap pass. Where a root's validity word is an
   * alias of one input's (every calendar extraction over a column, the mod-7 family), the
   * destination bitmap is that input's bitmap, whole-batch, and the loop's per-lane-group
   * {@code orValidityBitsAt} was writing it sixteen rows at a time.
   *
   * <p>Same bit-exactness rule as {@link #setValid}: {@code assertSameOutput} compares this
   * against the loop's own output byte for byte, and the loop leaves the bits past
   * {@code rows} at zero. The whole bytes are {@link MemorySegment#copy}, which is one
   * intrinsic and, unlike a hand-rolled ascending loop, is defined under any overlap; only
   * the final partial byte is masked by hand.
   *
   * <p>See {@link #andValidity} for the aliasing contract the three share. It matters here in
   * one extra way: {@code copyValidity(seg, seg, rows)} is not a no-op, because the tail write
   * clears the bits above {@code rows} in {@code seg}'s final byte.
   */
  public static void copyValidity(MemorySegment dst, MemorySegment src, int rows) {
    int wholeBytes = rows >>> 3;
    if (wholeBytes > 0) {
      MemorySegment.copy(src, 0L, dst, 0L, wholeBytes);
    }
    int tail = rows & 7;
    if (tail != 0) {
      dst.set(ValueLayout.JAVA_BYTE, wholeBytes,
          (byte) (src.get(ValueLayout.JAVA_BYTE, wholeBytes) & ((1 << tail) - 1)));
    }
  }

  /**
   * {@code dst = a & b} over exactly the low {@code rows} bits, zero past them - the
   * null-intolerant rule of the word algebra ( {@code AddDays}, {@code DateDiff},
   * {@code AddMonths} with a column count, {@code next_day} and {@code trunc} with a derived
   * column) taken over the whole batch at once.
   *
   * <p><b>The aliasing contract, shared by all three.</b> Each operand must be either disjoint
   * from {@code dst} or exactly {@code dst} - the same segment at the same offset. Being
   * allowed to be {@code dst} is what lets a nested expression be evaluated inner-first into
   * the destination with no scratch buffer. Partial overlap is <i>not</i> supported and is not
   * checked: the whole-byte loop runs ascending eight bytes at a time, so a destination one to
   * seven bytes ahead of an operand in the same buffer would read back what it had already
   * written. No caller can produce that - a validity bitmap is a whole buffer, mapped at its
   * own base - and paying for a direction check on a per-batch call to rule out a shape the
   * emitter cannot emit would be the wrong trade.
   *
   * <p>An operand that <i>is</i> the destination is written, not merely read, and the tail
   * write clears the bits above {@code rows} in its final byte. Every other operand is left
   * exactly as it was; {@code VarkaVectorSupportBitmapAlgebraTest} asserts that.
   */
  public static void andValidity(MemorySegment dst, MemorySegment a, MemorySegment b, int rows) {
    int wholeBytes = rows >>> 3;
    long i = 0;
    for (; i + 8 <= wholeBytes; i += 8) {
      dst.set(UNALIGNED_LONG, i, a.get(UNALIGNED_LONG, i) & b.get(UNALIGNED_LONG, i));
    }
    for (; i < wholeBytes; i++) {
      dst.set(ValueLayout.JAVA_BYTE, i,
          (byte) (a.get(ValueLayout.JAVA_BYTE, i) & b.get(ValueLayout.JAVA_BYTE, i)));
    }
    int tail = rows & 7;
    if (tail != 0) {
      dst.set(ValueLayout.JAVA_BYTE, wholeBytes, (byte) (a.get(ValueLayout.JAVA_BYTE, wholeBytes)
          & b.get(ValueLayout.JAVA_BYTE, wholeBytes) & ((1 << tail) - 1)));
    }
  }

  /**
   * {@code dst = a | b} over exactly the low {@code rows} bits, zero past them - the
   * null-skipping rule ({@code greatest}, {@code least}) over the whole batch. Same aliasing
   * and tail contract as {@link #andValidity}, which states it.
   */
  public static void orValidity(MemorySegment dst, MemorySegment a, MemorySegment b, int rows) {
    int wholeBytes = rows >>> 3;
    long i = 0;
    for (; i + 8 <= wholeBytes; i += 8) {
      dst.set(UNALIGNED_LONG, i, a.get(UNALIGNED_LONG, i) | b.get(UNALIGNED_LONG, i));
    }
    for (; i < wholeBytes; i++) {
      dst.set(ValueLayout.JAVA_BYTE, i,
          (byte) (a.get(ValueLayout.JAVA_BYTE, i) | b.get(ValueLayout.JAVA_BYTE, i)));
    }
    int tail = rows & 7;
    if (tail != 0) {
      dst.set(ValueLayout.JAVA_BYTE, wholeBytes, (byte) ((a.get(ValueLayout.JAVA_BYTE, wholeBytes)
          | b.get(ValueLayout.JAVA_BYTE, wholeBytes)) & ((1 << tail) - 1)));
    }
  }

  /**
   * The three helpers above take bitmaps. A column does not always have one, and whether it does
   * is known only at runtime, so these are the entry points the driver's bitmap pass emits: a
   * column's validity as the morsel contract spells it, an address beside a null count, with the
   * three states resolved here rather than as a branch ladder in the emitted driver.
   *
   * <p>{@code nulls == 0} means the column has no null row and no bitmap was materialised - the
   * operand is all ones. {@code nulls == rows} means every row is null, and the address is
   * {@code 0L} by the same contract and must not be dereferenced - the operand is all zeros.
   * Between the two the address is a bitmap, mapped here at exactly {@code (rows + 7) / 8}
   * bytes, which is what restores the bound the {@link MemorySegment} operands carry for free:
   * the raw {@code long} the driver holds does not, and milestone 1's finding 1 was a read one
   * byte past a validity buffer.
   *
   * <p>All ones is the identity of an AND and annihilates an OR; all zeros is the reverse. That
   * asymmetry is the whole reason these exist: an earlier draft of the plan had one rule for
   * both operators, which on {@code greatest(d, d2)} with a null-free {@code d} would have
   * marked null every row where {@code greatest} returns {@code d}'s value.
   *
   * <p>This one is the degenerate case, a single operand: {@code dst} is a copy of the column's
   * bitmap, or all ones, or all zeros.
   */
  public static void copyColumnValidity(MemorySegment dst, long srcAddr, int srcNulls, int rows) {
    requireNullCount(srcNulls, rows);
    if (srcNulls == 0) {
      setValid(dst, rows);
    } else if (srcNulls == rows) {
      zeroValidity(dst, rows);
    } else {
      copyValidity(dst, validityOf(srcAddr, rows), rows);
    }
  }

  /**
   * {@code dst = a & b} over two columns - the null-intolerant rule. An all-null operand decides
   * the whole expression; an all-ones operand drops out of it, leaving the other alone, and if
   * both drop out the answer is the constant {@link #setValid} writes.
   *
   * <p>The all-null test comes first so that a column with no bitmap is never mapped. See
   * {@link #copyColumnValidity} for the contract the three states come from.
   */
  public static void andColumnValidity(
      MemorySegment dst, long aAddr, int aNulls, long bAddr, int bNulls, int rows) {
    requireNullCount(aNulls, rows);
    requireNullCount(bNulls, rows);
    if (aNulls == rows || bNulls == rows) {
      zeroValidity(dst, rows);
    } else if (aNulls == 0) {
      copyColumnValidity(dst, bAddr, bNulls, rows);
    } else if (bNulls == 0) {
      copyColumnValidity(dst, aAddr, aNulls, rows);
    } else {
      andValidity(dst, validityOf(aAddr, rows), validityOf(bAddr, rows), rows);
    }
  }

  /**
   * {@code dst = a | b} over two columns - the null-skipping rule of {@code greatest} and
   * {@code least}. Mirror of {@link #andColumnValidity}: an all-ones operand decides the whole
   * expression and an all-null one drops out of it.
   */
  public static void orColumnValidity(
      MemorySegment dst, long aAddr, int aNulls, long bAddr, int bNulls, int rows) {
    requireNullCount(aNulls, rows);
    requireNullCount(bNulls, rows);
    if (aNulls == 0 || bNulls == 0) {
      setValid(dst, rows);
    } else if (aNulls == rows) {
      copyColumnValidity(dst, bAddr, bNulls, rows);
    } else if (bNulls == rows) {
      copyColumnValidity(dst, aAddr, aNulls, rows);
    } else {
      orValidity(dst, validityOf(aAddr, rows), validityOf(bAddr, rows), rows);
    }
  }

  /**
   * {@code dst = dst & b} over one more column: the step the bitmap pass takes for the third and
   * later operands of a flattened AND, once the first two have been written by
   * {@link #andColumnValidity(MemorySegment, long, int, long, int, int)}. The same three
   * states, read against a destination that already holds exactly {@code rows} bits: an
   * all-ones column leaves it as it is, an all-null one makes it all zeros, and a bitmap is
   * ANDed in place - {@link #andValidity} with the destination as its own first operand,
   * which the aliasing contract allows and which is the whole reason no scratch is needed.
   */
  public static void andColumnValidityInto(MemorySegment dst, long bAddr, int bNulls, int rows) {
    requireNullCount(bNulls, rows);
    if (bNulls == 0) {
      return;
    }
    if (bNulls == rows) {
      zeroValidity(dst, rows);
      return;
    }
    andValidity(dst, dst, validityOf(bAddr, rows), rows);
  }

  /**
   * {@code dst = dst | b} over one more column - the OR chain's step, mirror of
   * {@link #andColumnValidityInto}: an all-ones column decides the whole result, an all-null
   * one drops out, a bitmap is ORed in place.
   */
  public static void orColumnValidityInto(MemorySegment dst, long bAddr, int bNulls, int rows) {
    requireNullCount(bNulls, rows);
    if (bNulls == 0) {
      setValid(dst, rows);
      return;
    }
    if (bNulls == rows) {
      return;
    }
    orValidity(dst, dst, validityOf(bAddr, rows), rows);
  }

  // ---------------------------------------------------------------------------------------------
  // The driver's per-output work, read from a plan the emitter bakes into the kernel
  // ---------------------------------------------------------------------------------------------

  /** Plan step: zero the output's validity, mapped at the bitmap's nominal size. */
  public static final char PLAN_ZERO = 'z';
  /** Plan step: zero the output's validity, mapped to its last whole 64-bit word. */
  public static final char PLAN_ZERO_WORDS = 'Z';
  /** Plan step: set exactly {@code rows} bits of the output's validity ({@link #setValid}). */
  public static final char PLAN_FILL = 'f';
  /** Plan step: copy one column's validity, the next char its ordinal. */
  public static final char PLAN_COPY = 'c';
  /** Plan step: AND of columns' validities, the next char their count, then the ordinals. */
  public static final char PLAN_AND = '&';
  /** Plan step: OR of columns' validities, the next char their count, then the ordinals. */
  public static final char PLAN_OR = '|';

  /**
   * Writes every output's validity before the kernel's loops run, as a plan says: the work the
   * emitted driver otherwise unrolls once per output. {@code plan} holds one step per output, in
   * output order: {@link #PLAN_ZERO} or {@link #PLAN_ZERO_WORDS} for an output the loops write a
   * lane group or a word at a time, which must read as all-null until they do; {@link #PLAN_FILL}
   * for an output a dense batch makes valid on every row; and {@link #PLAN_COPY},
   * {@link #PLAN_AND} or {@link #PLAN_OR} with their column ordinals for an output the whole-batch
   * bitmap pass writes from its inputs' bitmaps, by the same entry points the unrolled pass calls.
   * The arrays are the kernel's own parameters, so the result is the unrolled driver's bit for
   * bit. The plan says how many outputs there are: {@code dstValidity} may be longer, as the
   * unrolled driver allowed, and is refused only when it is shorter.
   *
   * <p>It exists for the driver's size: unrolled, this work is about forty bytes of bytecode an
   * output, and the driver is the one method no regroup shrinks, so it was what capped a kernel's
   * width. As a plan it is one call whatever the width. See {@code PLAN_TASK_190.md} 9.2.
   */
  public static void prepareOutputValidity(long[] dstValidity, long[] srcValidity,
      int[] nullCounts, String plan, int rows) {
    long nominal = (rows + 7) / 8;
    int at = 0;
    for (int o = 0; at < plan.length(); o++) {
      if (o >= dstValidity.length) {
        throw new IllegalArgumentException("output plan names output " + o + " and the kernel "
            + "was given " + dstValidity.length + " destinations");
      }
      char step = plan.charAt(at++);
      switch (step) {
        case PLAN_ZERO -> zero(ofAddress(dstValidity[o], nominal));
        case PLAN_ZERO_WORDS -> zero(ofAddress(dstValidity[o], ((rows + 63L) / 64) * 8));
        case PLAN_FILL -> setValid(ofAddress(dstValidity[o], nominal), rows);
        case PLAN_COPY -> {
          int c = plan.charAt(at++);
          copyColumnValidity(ofAddress(dstValidity[o], nominal), srcValidity[c], nullCounts[c],
              rows);
        }
        case PLAN_AND, PLAN_OR -> {
          int n = plan.charAt(at++);
          int a = plan.charAt(at++);
          int b = plan.charAt(at++);
          MemorySegment dst = ofAddress(dstValidity[o], nominal);
          if (step == PLAN_AND) {
            andColumnValidity(dst, srcValidity[a], nullCounts[a], srcValidity[b], nullCounts[b],
                rows);
          } else {
            orColumnValidity(dst, srcValidity[a], nullCounts[a], srcValidity[b], nullCounts[b],
                rows);
          }
          for (int k = 2; k < n; k++) {
            int c = plan.charAt(at++);
            if (step == PLAN_AND) {
              andColumnValidityInto(dst, srcValidity[c], nullCounts[c], rows);
            } else {
              orColumnValidityInto(dst, srcValidity[c], nullCounts[c], rows);
            }
          }
        }
        default -> throw new IllegalArgumentException(
            "unknown output plan step '" + step + "' for output " + o);
      }
    }
  }

  /**
   * Whether every output reads at least one all-null column - the masked driver's all-null
   * shortcut, which then returns before any loop runs. {@code columns} holds, per output in
   * order, the count of the columns it reads and then their ordinals; a column is all-null when
   * its null count is the batch's length. The table form of the test the driver otherwise
   * unrolls once per output; see {@link #prepareOutputValidity}.
   */
  public static boolean everyOutputReadsAnAllNullColumn(int[] nullCounts, String columns,
      int rows) {
    int at = 0;
    while (at < columns.length()) {
      int n = columns.charAt(at++);
      boolean any = false;
      for (int k = 0; k < n; k++) {
        any |= nullCounts[columns.charAt(at + k)] == rows;
      }
      if (!any) {
        // One output with no all-null column is enough: the shortcut is off for the batch, which
        // is the common case, so it is answered without reading the rest of the table.
        return false;
      }
      at += n;
    }
    return true;
  }

  /** A column's validity bitmap at exactly the bytes {@code rows} bits occupy, and no more. */
  private static MemorySegment validityOf(long addr, int rows) {
    return ofAddress(addr, (rows + 7) / 8);
  }

  /**
   * The three-state contract these entry points read a column by: {@code 0 <= nulls <= rows},
   * with the ends meaning all-ones and all-zeros and no bitmap materialised at either.
   *
   * <p>Checked rather than tolerated because the emitted driver encodes the same states with
   * {@code nullCount == length} while an earlier form of these methods used {@code >= rows}:
   * for a column reporting more nulls than the caller's row count the two disagreed, and one
   * batch could then have reported a column all-null for a served output and per-row valid for
   * an unserved one. The production caller cannot produce that - {@code extractMorsel}
   * requires the vector's value count to equal the batch's length - but the engine's own
   * {@code VarkaMorsel.extractDate} maps a prefix of a longer vector while reporting the whole
   * vector's null count, so the shape exists at this module's public boundary and is refused
   * here rather than answered two ways.
   */
  private static void requireNullCount(int nulls, int rows) {
    if (nulls < 0 || nulls > rows) {
      throw new IllegalArgumentException(
          "null count " + nulls + " outside [0, " + rows + "]");
    }
  }

  /**
   * Clears exactly the bytes {@code rows} bits occupy. Not {@link #zero}, which clears the whole
   * segment: {@code dst} is mapped at the bitmap's size in every kernel today, so the two agree,
   * and stating the length here keeps that an assumption these helpers do not depend on.
   */
  private static void zeroValidity(MemorySegment dst, int rows) {
    int bitmapBytes = (rows + 7) / 8;
    if (bitmapBytes > 0) {
      dst.asSlice(0L, bitmapBytes).fill((byte) 0);
    }
  }

  /**
   * Maps a raw address as a segment of exactly {@code bytes} bytes. The size is the whole point:
   * the caller passes a bare {@code long}, so this is where a kernel says how far it is entitled
   * to read, and the {@link MemorySegment} bounds check enforces it from there on.
   */
  public static MemorySegment ofAddress(long addr, long bytes) {
    return MemorySegment.ofAddress(addr).reinterpret(bytes);
  }
}
