/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.catalyst.expressions.codegen

import java.util.concurrent.ConcurrentHashMap

/**
 * A per-task class loader for Varka Class-File generated bytecode, mirroring the engine
 * module's `org.apache.spark.sql.varka.execution.VarkaClassLoader` so the two sides of the
 * MVP share the same unload contract. The registry + `findClass` mirror Spark's
 * `InMemoryClassLoader` (CodeCompiler.scala), so callers can use `loadClass(name)` after
 * [[defineGeneratedClass]].
 *
 * The duplication with the engine's copy is deliberate, not an oversight waiting to be
 * deduplicated: neither module can depend on the other. The engine is only a test-scope
 * dependency here and at runtime is deployed externally (`--jars`) - so catalyst cannot
 * compile against it - while the engine in turn cannot depend on catalyst. The two classes
 * are therefore kept deliberately identical in behaviour, and a change to one belongs in
 * the other.
 */
private[sql] class VarkaGeneratedClassLoader(parent: ClassLoader) extends ClassLoader(parent) {

  private val definedClasses = new ConcurrentHashMap[String, Class[_]]()

  @volatile private var released = false

  /** Defines a generated class and registers it so `loadClass(name)` resolves it. */
  def defineGeneratedClass(className: String, bytes: Array[Byte]): Class[_] = {
    if (released) {
      throw new IllegalStateException("VarkaGeneratedClassLoader has already been released")
    }
    val clazz = defineClass(className, bytes, 0, bytes.length)
    definedClasses.put(className, clazz)
    clazz
  }

  /** Marks the loader released and clears the class registry. Idempotent and thread-safe. */
  def release(): Unit = {
    released = true
    definedClasses.clear()
  }

  def isReleased: Boolean = released

  override protected def findClass(name: String): Class[_] = {
    val clazz = definedClasses.get(name)
    if (clazz != null) {
      clazz
    } else {
      throw new ClassNotFoundException(name)
    }
  }
}
