/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.catalyst.expressions.codegen.varka

import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.security.MessageDigest

import scala.jdk.CollectionConverters._

import com.fasterxml.jackson.databind.{JsonNode, ObjectMapper}

import org.apache.spark.SparkFunSuite
import org.apache.spark.sql.catalyst.expressions.{Alias, Attribute, AttributeReference,
  Expression, In, InSet, Literal}
import org.apache.spark.sql.catalyst.expressions.codegen.VarkaExpressionCompiler
import org.apache.spark.sql.catalyst.expressions.codegen.varka.VarkaIrGrammar._
import org.apache.spark.sql.catalyst.expressions.codegen.varka.VarkaVectorIR.LaneType
import org.apache.spark.sql.catalyst.parser.CatalystSqlParser
import org.apache.spark.sql.types.{DateType, DayTimeIntervalType, IntegerType, LongType,
  TimeType, YearMonthIntervalType}

/**
 * The emitted-bytes oracle (task 85, step 1): what the emitter produces for every shape, pinned
 * so that a refactor of the emitter can prove it changed nothing. It is also the check that the
 * compiler never builds IR the emitter rejects: every coverage row goes through the compiler and
 * is emitted at both widths, and an emitter rejection of any of them fails this suite
 * (`PLAN_TASK_169.md` 2.1, the IR contract violations).
 *
 * Three shape sets. Every row of the coverage table (`sql/varka/coverage.json`, compiled to IR
 * the way `VarkaCoverageSuite` compiles it, on both lanes), ten thousand random int32 trees
 * from the shared fuzz grammar at a fixed seed, and ten thousand random long-lane trees from
 * its long grammar at that grammar's own seed (task 119). Each shape is emitted at two widths,
 * 128 and 512 bits - `lanesOverride` 4 and 16 at the int lane, 2 and 8 at the long one - and
 * every method body of the emitted class is rendered symbolically
 * (`VarkaEmitterTestSupport.methodBodies`: opcodes and resolved operands, labels numbered, no
 * constant-pool indices and no line tables) and hashed.
 *
 * What `sql/varka/emitted_bytes.json` pins: for each width, one hash per method per coverage
 * row, so a difference on a named shape says which method moved; and, for each fuzz sequence,
 * one digest per block of a hundred shapes, so a difference names the block and the suite can
 * re-emit that block to find the shape. The committed file is generated by this suite and
 * compared byte for byte, on `VarkaCoverageSuite`'s precedent:
 *
 * {{{
 *   VARKA_BYTES_REGEN=true build/sbt 'catalyst/testOnly *VarkaEmittedBytesSuite'
 * }}}
 *
 * A difference is a change in what an emitted method does. It is not always a bug - a task
 * that means to change the emitted code regenerates the file and says so in its plan - but it
 * is never a note: the step that produced it reads the two renderings before it is accepted.
 */
class VarkaEmittedBytesSuite extends SparkFunSuite {

  private val seed = fuzzSeed
  private val shapes = 10000
  private val blockSize = 100
  private val widths = Seq(4, 16)

  // The coverage table's columns, as `VarkaCoverageSuite` declares them.
  private val d = AttributeReference("d", DateType)()
  private val d2 = AttributeReference("d2", DateType)()
  private val i = AttributeReference("i", IntegerType)()
  private val ymm = AttributeReference("ymm",
    YearMonthIntervalType(YearMonthIntervalType.MONTH, YearMonthIntervalType.MONTH))()
  private val ymy = AttributeReference("ymy",
    YearMonthIntervalType(YearMonthIntervalType.YEAR, YearMonthIntervalType.YEAR))()
  private val ym = AttributeReference("ym",
    YearMonthIntervalType(YearMonthIntervalType.YEAR, YearMonthIntervalType.MONTH))()
  private val l = AttributeReference("l", LongType)()
  private val l2 = AttributeReference("l2", LongType)()
  private val t = AttributeReference("t", TimeType(6))()
  private val t2 = AttributeReference("t2", TimeType(6))()
  private val dt = AttributeReference("dt", DayTimeIntervalType())()
  private val dt2 = AttributeReference("dt2", DayTimeIntervalType())()
  private val columns: Seq[Attribute] = Seq(d, d2, i, ymm, ymy, ym, l, l2, t, t2, dt, dt2)

  private val className = "org.apache.spark.sql.varka.execution.VarkaEmittedBytesOracle"

  private def sha(text: String): String = {
    val digest = MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8))
    digest.take(8).map(b => f"$b%02x").mkString
  }

  /**
   * What the emitted class is, hashed: one entry per method - its name and descriptor to the
   * hash of its rendered body, in declaration order - and one for the class around them, under
   * the key `<class>`, which no method entry can collide with because a method's key always
   * carries its descriptor's parentheses. The class entry covers what the bodies cannot: the
   * flags, the interfaces, the attribute names, and each method's own flags. Without it a
   * refactor could drop the `VarkaFusedKernel` interface or the telemetry attribute and every
   * body would still render identically.
   */
  private def methodHashes(roots: Seq[VarkaVectorIR], numInputs: Int, numLiterals: Int,
      lanes: Int,
      arm: VarkaEmitOptions => VarkaEmitOptions = identity): Seq[(String, String)] = {
    // `lanes` is the int lane's count, and names a width: 4 lanes are 128 bits and 16 are 512.
    // A long-lane shape is emitted at the same two widths, which are 2 and 8 of its lanes;
    // sixteen 64-bit lanes would be a species that does not exist, and the emitter would fall
    // back to SPECIES_PREFERRED and pin nothing about width. The lane asked for is the
    // emission's, which for a narrowing root (an int output computed in the long lane) is the
    // long lane.
    val laneCount =
      if (VarkaVectorIR.emissionLane(roots.head) == LaneType.LONG) lanes / 2 else lanes
    // The arm is applied over the width, not under it: every arm below leaves the lane count
    // alone, and the oracle's two widths are what the arm is being compared across.
    val options = arm(VarkaEmitOptions.DEFAULTS.withLanesOverride(laneCount))
    val bytes =
      try {
        VarkaLoopEmitter.emit(className, roots.asJava, numInputs, numLiterals, null, null, options)
      } catch {
        // An arm may decline a shape the defaults emit (task 87's byte budget on a heavy single
        // output); the audit records that as the arm's answer rather than failing on it.
        case d: VarkaEmitDeclined => return Seq("<declined>" -> sha(d.getMessage))
      }
    ("<class>" -> sha(VarkaEmitterTestSupport.classSummary(bytes))) +:
      VarkaEmitterTestSupport.methodBodies(bytes).asScala.toSeq.map { case (m, body) =>
        m -> sha(body)
      }
  }

  // ---------------------------------------------------------------------------------------
  // The coverage rows
  // ---------------------------------------------------------------------------------------

  private case class CoverageShape(sql: String, roots: Seq[VarkaVectorIR], numInputs: Int,
      numLiterals: Int)

  /**
   * The row as the optimizer would hand it to the compiler. There is no optimizer here - the SQL
   * is parsed and resolved and that is all - so a row the table records as arriving as an `InSet`
   * would otherwise be pinned through the compiler's `In` arm, which is not the arm production
   * takes. `OptimizeIn`'s rewrite is the only such difference the table has; the row's own
   * `catalyst` field says which rows it applies to.
   */
  private def asCatalystClaims(expr: Expression, catalyst: Set[String]): Expression = expr match {
    case In(value, list) if catalyst.contains("InSet") && list.forall(_.isInstanceOf[Literal]) =>
      InSet(value, list.map(_.asInstanceOf[Literal].value).toSet)
    case other if catalyst.contains("InSet") =>
      // The rewrite is the only thing standing between this row and the wrong compiler arm, so
      // a row that claims InSet and does not get one fails rather than being pinned quietly.
      fail(s"a row the table records as an InSet resolved to ${other.getClass.getSimpleName}: " +
        "the executable spelling and the catalyst field disagree")
    case other => other
  }

  /**
   * Every row of the table as IR, through the compiler: a projection row's compiled outputs, a
   * predicate row's fused condition root.
   *
   * Two ways a row can fail to produce IR, and they are not the same thing. A row whose SQL does
   * not parse is recorded as skipped, by name, so the file says what it does not pin; the table
   * carries an `executable` spelling for every row today, so the list is empty and a name
   * appearing in it is a table that grew a caption. A row that parses and then declines is a
   * coverage regression - `VarkaCoverageSuite` asserts every row fuses - so it fails here
   * rather than quietly moving into that list, where a regeneration would bless it.
   */
  private lazy val coverage: (Seq[CoverageShape], Seq[String]) = {
    val file = getWorkspaceFilePath("sql", "varka", "coverage.json").toFile
    val doc = new ObjectMapper().readTree(file)
    val shapes = Seq.newBuilder[CoverageShape]
    val skipped = Seq.newBuilder[String]
    doc.get("expressions").elements().asScala.foreach { e =>
      val sql = e.get("sql").asText()
      val executable = Option(e.get("executable")).map(_.asText()).getOrElse(sql)
      val form = e.get("form").asText()
      val catalyst = Option(e.get("catalyst"))
        .map(_.elements().asScala.map(_.asText()).toSet).getOrElse(Set.empty[String])
      // The parse guard covers the parse and the resolve, and nothing else: `asCatalystClaims`
      // fails the suite on purpose when a row's spelling and its catalyst field disagree, and a
      // catch around it would turn that into a silent skip.
      val parsed: Option[Expression] =
        try Some(VarkaSqlResolve.resolve(CatalystSqlParser.parseExpression(executable), columns))
        catch { case _: Exception => None }
      val resolved = parsed.map(asCatalystClaims(_, catalyst))
      val compiled = resolved.flatMap { expr =>
        if (form == "predicate") {
          VarkaExpressionCompiler.compilePredicate(expr, columns).map(_.fused)
        } else {
          VarkaExpressionCompiler.compile(Seq(Alias(expr, "c")()), columns)
        }
      }
      compiled match {
        case Some(c) =>
          shapes += CoverageShape(sql, c.outputs, c.inputOrdinals.size, c.numLiterals)
        case None if resolved.isEmpty => skipped += sql
        case None =>
          fail(s"coverage row does not fuse, so the oracle cannot pin it: $sql. " +
            "VarkaCoverageSuite asserts every row fuses; fix that first.")
      }
    }
    (shapes.result(), skipped.result())
  }

  // ---------------------------------------------------------------------------------------
  // The fuzz sequence
  // ---------------------------------------------------------------------------------------

  private case class FuzzShape(roots: Seq[VarkaVectorIR], numInputs: Int, numLiterals: Int)

  /**
   * Shape `k` of the sequence: `VarkaIrGrammar`'s draw, from `VarkaIrGrammar`'s seed, through
   * `VarkaIrGrammar`'s generator - all three shared with `VarkaIrFuzzSuite`, so shape `k` here
   * is shape `k` there. This suite pins ten thousand of them and that suite checks the first
   * three hundred against the reference evaluator by default, so the corpora are one sequence
   * with two depths rather than two sequences: every shape the fuzzer checks is pinned here,
   * and a shape beyond that prefix is one the fuzzer checks when its iteration count is raised.
   * Copies of the draw, the seed or the generator in each suite would let them part company
   * with no test noticing, which is why none of the three lives here.
   */
  private def fuzzShape(k: Int): FuzzShape = {
    val drawn = drawShape(shapeRandom(seed, k))
    FuzzShape(drawn.roots, drawn.numInputs, drawn.numLiterals)
  }

  /**
   * Shape `k` of the long-lane sequence, the same way: `VarkaIrGrammar`'s long draw from its
   * long seed, which `VarkaIrFuzzSuite` runs against `evalLong`.
   */
  private def longFuzzShape(k: Int): FuzzShape = {
    val drawn = drawLongShape(shapeRandom(longFuzzSeed, k))
    FuzzShape(drawn.roots, drawn.numInputs, drawn.numLiterals)
  }

  /** The digest of one block of a sequence at one width. */
  private def blockDigest(shapeAt: Int => FuzzShape, block: Int, lanes: Int): String = {
    val sb = new StringBuilder
    for (k <- block * blockSize until math.min((block + 1) * blockSize, shapes)) {
      val s = shapeAt(k)
      sb.append(k).append(':')
      methodHashes(s.roots, s.numInputs, s.numLiterals, lanes).foreach { case (m, h) =>
        sb.append(' ').append(m).append('=').append(h)
      }
      sb.append('\n')
    }
    sha(sb.toString)
  }

  // ---------------------------------------------------------------------------------------
  // The file
  // ---------------------------------------------------------------------------------------

  /**
   * The emit options a session can select, and so the emissions the oracle has to pin.
   *
   * Only one field of `VarkaEmitOptions` has a configuration in front of it -
   * `spark.sql.codegen.varka.emit.useAVX`, which task 121 added so that a machine whose
   * converts do not become instructions can ask for the magic form. Everything else on the
   * record reaches the emitter through a test hook alone, and the audit test below records
   * which of those move bytes. The oracle therefore pins the defaults in full, shape by
   * shape, and each of these arms as one digest per width: a digest is enough to catch a
   * change, and pinning five arms shape by shape would multiply a large file by five to say
   * the same thing.
   *
   * A level the emitter treats as the default is pinned anyway. It costs a line and it is the
   * only way the file can show that `useAVX=3` and an unstated level really do emit alike.
   */
  private def pinnedArms: Seq[(String, VarkaEmitOptions => VarkaEmitOptions)] =
    Seq(VarkaEmitOptions.USE_AVX_UNKNOWN, 0, 1, 2, 3).map { level =>
      s"useAVX=$level" -> ((o: VarkaEmitOptions) => o.withUseAVX(level))
    }

  /** One hash over every shape the oracle holds, emitted under `arm` at `lanes`. */
  private def armDigest(arm: VarkaEmitOptions => VarkaEmitOptions, lanes: Int): String = {
    val sb = new StringBuilder
    val (rows, _) = coverage
    rows.foreach { r =>
      sb.append(r.sql)
      methodHashes(r.roots, r.numInputs, r.numLiterals, lanes, arm).foreach { case (m, h) =>
        sb.append(' ').append(m).append('=').append(h)
      }
      sb.append('\n')
    }
    Seq(fuzzShape _, longFuzzShape _).foreach { shapeAt =>
      for (k <- 0 until shapes) {
        val sh = shapeAt(k)
        sb.append(k)
        methodHashes(sh.roots, sh.numInputs, sh.numLiterals, lanes, arm).foreach {
          case (m, h) => sb.append(' ').append(m).append('=').append(h)
        }
        sb.append('\n')
      }
    }
    sha(sb.toString)
  }

  private def render(): String = {
    def ordered(pairs: (String, Any)*): java.util.LinkedHashMap[String, Any] = {
      val map = new java.util.LinkedHashMap[String, Any]()
      pairs.foreach { case (k, v) => map.put(k, v) }
      map
    }
    val (rows, skipped) = coverage
    val perWidth = widths.map { lanes =>
      val coverageHashes = ordered(rows.map { r =>
        r.sql -> ordered(methodHashes(r.roots, r.numInputs, r.numLiterals, lanes): _*)
      }: _*)
      val blockCount = (shapes + blockSize - 1) / blockSize
      val blocks = (0 until blockCount).map(blockDigest(fuzzShape, _, lanes))
      val longBlocks = (0 until blockCount).map(blockDigest(longFuzzShape, _, lanes))
      lanes.toString -> ordered(
        "coverage" -> coverageHashes,
        "fuzz" -> ordered(
          "seed" -> seed, "shapes" -> shapes, "block_size" -> blockSize,
          "blocks" -> blocks.asJava),
        "fuzz_long" -> ordered(
          "seed" -> longFuzzSeed, "shapes" -> shapes, "block_size" -> blockSize,
          "blocks" -> longBlocks.asJava))
    }
    val armHashes = ordered(pinnedArms.map { case (name, arm) =>
      name -> ordered(widths.map(w => w.toString -> armDigest(arm, w)): _*)
    }: _*)
    val doc = ordered(
      "generated_by" -> ("VarkaEmittedBytesSuite; regenerate with VARKA_BYTES_REGEN=true " +
        "build/sbt 'catalyst/testOnly *VarkaEmittedBytesSuite'"),
      "description" -> ("Hashes of every emitted method body, rendered symbolically, for every " +
        "coverage row and for a fixed sequence of fuzz shapes at each lane, at 128 and 512 bits " +
        "(lanesOverride 4 and 16 at the int lane, 2 and 8 at the long one). A difference is a " +
        "change in what an emitted method does. `option_arms` covers the emissions a session " +
        "can select rather than only the defaults: one digest over every shape at each width " +
        "per value of spark.sql.codegen.varka.emit.useAVX, the only emit option a " +
        "configuration reaches. The rest of VarkaEmitOptions is test-only."),
      "coverage_rows_skipped" -> skipped.asJava,
      "lanes" -> ordered(perWidth: _*),
      "option_arms" -> armHashes)
    new ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(doc) + "\n"
  }

  private def regenerate: Boolean = sys.env.get("VARKA_BYTES_REGEN").contains("true")

  test("sql/varka/emitted_bytes.json pins what the emitter produces for every shape") {
    val path = getWorkspaceFilePath("sql", "varka", "emitted_bytes.json")
    val rendered = render()
    if (regenerate) {
      Files.write(path, rendered.getBytes(StandardCharsets.UTF_8))
      logInfo(s"regenerated $path")
    } else {
      assert(Files.exists(path), s"$path is missing; generate it with\n" +
        "  VARKA_BYTES_REGEN=true build/sbt 'catalyst/testOnly *VarkaEmittedBytesSuite'")
      val committed = new String(Files.readAllBytes(path), StandardCharsets.UTF_8)
      if (committed != rendered) {
        // Name what moved before failing: the coverage rows and methods whose hash differs,
        // and the fuzz blocks, so the reader goes straight to a shape. Both directions are
        // walked - a row or a method that *vanished* is the more alarming of the two, since it
        // means a shape the table claims stopped reaching the emitter, and reporting only
        // additions would leave the loudest failure with nothing to print.
        val mapper = new ObjectMapper()
        val before = mapper.readTree(committed)
        val after = mapper.readTree(rendered)
        val moved = Seq.newBuilder[String]
        def keysOf(node: JsonNode): Set[String] =
          if (node == null) Set.empty else node.fieldNames().asScala.toSet
        def hashOf(node: JsonNode, key: String): Option[String] =
          Option(node).flatMap(n => Option(n.get(key))).map(_.asText())
        def skipsOf(doc: JsonNode): Set[String] =
          Option(doc.get("coverage_rows_skipped"))
            .map(_.elements().asScala.map(_.asText()).toSet).getOrElse(Set.empty)
        val committedSkips = skipsOf(before)
        val renderedSkips = skipsOf(after)
        (committedSkips -- renderedSkips).foreach(r => moved += s"no longer skipped: $r")
        (renderedSkips -- committedSkips).foreach(r => moved += s"newly skipped: $r")
        widths.foreach { lanes =>
          val b = Option(before.get("lanes")).map(_.get(lanes.toString)).orNull
          val a = after.get("lanes").get(lanes.toString)
          if (b == null) {
            moved += s"lanes $lanes: no committed entry"
          } else {
            val bCoverage = b.get("coverage")
            val aCoverage = a.get("coverage")
            (keysOf(bCoverage) -- keysOf(aCoverage)).foreach { row =>
              moved += s"lanes $lanes: row gone $row"
            }
            (keysOf(aCoverage) -- keysOf(bCoverage)).foreach { row =>
              moved += s"lanes $lanes: new row $row"
            }
            (keysOf(aCoverage) intersect keysOf(bCoverage)).foreach { row =>
              val was = bCoverage.get(row)
              val now = aCoverage.get(row)
              (keysOf(was) -- keysOf(now)).foreach { m =>
                moved += s"lanes $lanes: $row method gone $m"
              }
              (keysOf(now) -- keysOf(was)).foreach { m =>
                moved += s"lanes $lanes: $row new method $m"
              }
              (keysOf(now) intersect keysOf(was)).foreach { m =>
                if (hashOf(was, m) != hashOf(now, m)) moved += s"lanes $lanes: $row method $m"
              }
            }
            Seq("fuzz", "fuzz_long").foreach { sequence =>
              val bb = Option(b.get(sequence)).map(_.get("blocks")).orNull
              val ab = a.get(sequence).get("blocks")
              ab.elements().asScala.zipWithIndex.foreach { case (n, k) =>
                if (bb == null || bb.size <= k || bb.get(k).asText() != n.asText()) {
                  moved += s"lanes $lanes: $sequence block $k (shapes ${k * blockSize} to " +
                    s"${(k + 1) * blockSize - 1})"
                }
              }
              if (bb != null && bb.size > ab.size) {
                moved += s"lanes $lanes: ${bb.size - ab.size} committed $sequence block(s) gone"
              }
            }
          }
        }
        if (moved.result().isEmpty) {
          // Every hash matched, so the difference is in the file around them: the preamble,
          // the fuzz parameters, or the formatting. Say so rather than printing nothing.
          moved += "no hash differs; the file's other content or its formatting changed"
        }
        fail("sql/varka/emitted_bytes.json does not match what the emitter produces. If the " +
          "emitted code was meant to change, regenerate with\n" +
          "  VARKA_BYTES_REGEN=true build/sbt 'catalyst/testOnly *VarkaEmittedBytesSuite'\n" +
          "and say so in the task's plan. What moved:\n  " + moved.result().mkString("\n  "))
      }
    }
  }

  test("the two widths differ where the lane count is baked in, so the oracle sees width") {
    // A single shape emitted at 4 and 16 lanes must render differently somewhere: the species
    // constant is baked into the class, and a width that left every method identical would
    // mean the override was ignored and the second width pins nothing.
    val (rows, _) = coverage
    assert(rows.nonEmpty)
    val r = rows.head
    val at4 = methodHashes(r.roots, r.numInputs, r.numLiterals, 4).toMap
    val at16 = methodHashes(r.roots, r.numInputs, r.numLiterals, 16).toMap
    assert(at4 != at16, s"${r.sql}: identical at 4 and 16 lanes")
  }

  // ---------------------------------------------------------------------------------------
  // The option audit (milestone 5 row 167), opt-in
  // ---------------------------------------------------------------------------------------

  /**
   * Every value of every emit option, paired with the transform that selects it.
   *
   * The oracle above pins the defaults, and only the defaults, at two widths. That was enough
   * while `VarkaEmitOptions` was reachable from tests alone; task 121 gave one of its fields a
   * session configuration, so a user can now ask for an emission no committed hash covers.
   * This list is the inventory row 167 asks for, and the test below turns it into the other
   * half of the answer: which of these arms actually move the emitted bytes, and on which
   * shapes.
   *
   * Booleans appear at both values rather than only the non-default one, so the report says in
   * its own numbers which value is the default - the arm that moves nothing is it - instead of
   * resting on a reader's memory of the DEFAULTS constructor. `lanesOverride` is absent because
   * the oracle already emits every shape at two widths, and the two budgets appear at values
   * that bracket the shipped ones rather than at every integer.
   */
  private def optionArms: Seq[(String, VarkaEmitOptions => VarkaEmitOptions)] = {
    val booleans = Seq[(String, (VarkaEmitOptions, Boolean) => VarkaEmitOptions)](
      "cse" -> (_.withCse(_)),
      "shareChronoPrefix" -> (_.withShareChronoPrefix(_)),
      "denseValidityOnce" -> (_.withDenseValidityOnce(_)),
      "elideChronoMonth" -> (_.withElideChronoMonth(_)),
      "neriSchneiderMonth" -> (_.withNeriSchneiderMonth(_)),
      "julianMap" -> (_.withJulianMap(_)),
      "guardDayProducers" -> (_.withGuardDayProducers(_)),
      "validityByWidth" -> (_.withValidityByWidth(_)),
      "validityOrFirst" -> (_.withValidityOrFirst(_)),
      "validityByBitmap" -> (_.withValidityByBitmap(_)),
      "checkIntOverflow" -> (_.withCheckIntOverflow(_)),
      "guardUnderArm" -> (_.withGuardUnderArm(_)),
      "shareWholeNodes" -> (_.withShareWholeNodes(_)),
      "validityByWord" -> (_.withValidityByWord(_)),
      "mulHiDivide" -> (_.withMulHiDivide(_)),
      "narrowHalfSpecies" -> (_.withNarrowHalfSpecies(_)),
      "misdescribeAdd" -> (_.withMisdescribeAdd(_)),
      "misdescribeWordLiveness" -> (_.withMisdescribeWordLiveness(_)))
    val flags = booleans.flatMap { case (name, set) =>
      Seq(true, false).map(v => s"$name=$v" -> ((o: VarkaEmitOptions) => set(o, v)))
    }
    val division = VarkaEmitOptions.Division.values.toSeq.map { d =>
      s"division=$d" -> ((o: VarkaEmitOptions) => o.withDivision(d))
    }
    val avx = Seq(VarkaEmitOptions.USE_AVX_UNKNOWN, 0, 1, 2, 3).map { level =>
      s"useAVX=$level" -> ((o: VarkaEmitOptions) => o.withUseAVX(level))
    }
    val budgets = Seq(
      "groupBudget=64" -> ((o: VarkaEmitOptions) => o.withGroupBudget(64)),
      "groupBudget=800" -> ((o: VarkaEmitOptions) => o.withGroupBudget(800)),
      "fusedCeiling=200" -> ((o: VarkaEmitOptions) => o.withFusedCeiling(200)),
      "fusedCeiling=800" -> ((o: VarkaEmitOptions) => o.withFusedCeiling(800)),
      "methodByteBudget=0" -> ((o: VarkaEmitOptions) => o.withMethodByteBudget(0)),
      "methodByteBudget=8000" -> ((o: VarkaEmitOptions) => o.withMethodByteBudget(8000)))
    flags ++ division ++ avx ++ budgets
  }

  /**
   * What each option arm does to the emitted bytes, over the oracle's own shapes.
   *
   * Opt-in because it emits every shape once per arm and takes minutes rather than seconds.
   * It asserts nothing about which arms move bytes - that is the finding, not a contract - and
   * writes a report the task reads. What it does assert is that the audit saw every shape it
   * meant to, so a report of "nothing moved" can never come from a loop that ran over an empty
   * list.
   *
   *   VARKA_OPTION_AUDIT=true build/sbt 'catalyst/testOnly *VarkaEmittedBytesSuite -- -z audit'
   */
  test("the option audit: which options move the emitted bytes, and on which shapes") {
    assume(sys.env.get("VARKA_OPTION_AUDIT").contains("true"),
      "opt-in: set VARKA_OPTION_AUDIT=true")
    val (rows, _) = coverage
    val sampled = 200
    val report = Seq.newBuilder[String]
    report += "# Which emit options move the emitted bytes, over the oracle's own shapes."
    report += "# Generated by VarkaEmittedBytesSuite's option audit (milestone 5 row 167)."
    report += f"# ${rows.size} coverage rows and $sampled fuzz shapes per lane, at widths " +
      widths.mkString(" and ") + " lanes."
    report += ""
    report += f"${"arm"}%-32s ${"coverage"}%10s ${"int fuzz"}%10s ${"long fuzz"}%10s"

    type Hashes = (Seq[Seq[(String, String)]], Seq[Seq[(String, String)]],
      Seq[Seq[(String, String)]])
    def hashesFor(arm: VarkaEmitOptions => VarkaEmitOptions, lanes: Int): Hashes = {
      val cover = rows.map(r => methodHashes(r.roots, r.numInputs, r.numLiterals, lanes, arm))
      val ints = (0 until sampled).map { k =>
        val sh = fuzzShape(k); methodHashes(sh.roots, sh.numInputs, sh.numLiterals, lanes, arm)
      }
      val longs = (0 until sampled).map { k =>
        val sh = longFuzzShape(k)
        methodHashes(sh.roots, sh.numInputs, sh.numLiterals, lanes, arm)
      }
      (cover, ints, longs)
    }

    val base = widths.map(w => w -> hashesFor(identity, w)).toMap
    assert(base(widths.head)._1.nonEmpty && base(widths.head)._2.size == sampled,
      "the audit emitted no shapes; a report from this run would mean nothing")

    optionArms.foreach { case (name, arm) =>
      var cover, ints, longs = 0
      // An arm is allowed to make emission fail, and two of them exist for exactly that: the
      // `misdescribe*` pair feeds the emitter a wrong descriptor or an inverted liveness
      // verdict so that its own self-checks can be shown to fire. An inventory records that
      // outcome; it must not be stopped by it, or every arm after the first fault injector
      // goes unmeasured.
      val raised = scala.util.Try {
        widths.foreach { w =>
          val (bc, bi, bl) = base(w)
          val (ac, ai, al) = hashesFor(arm, w)
          cover += bc.zip(ac).count { case (b, a) => b != a }
          ints += bi.zip(ai).count { case (b, a) => b != a }
          longs += bl.zip(al).count { case (b, a) => b != a }
        }
      }.failed.toOption
      val line = raised match {
        case Some(e) =>
          f"$name%-32s ${"raises"}%10s ${e.getClass.getSimpleName}%s: " +
            Option(e.getMessage).getOrElse("").take(70)
        case None => f"$name%-32s $cover%10d $ints%10d $longs%10d"
      }
      report += line
      // scalastyle:off println
      println("option audit  " + line)
      // scalastyle:on println
    }
    val out = new java.io.File("target/varka-option-audit.txt")
    Option(out.getParentFile).foreach(_.mkdirs())
    java.nio.file.Files.write(out.toPath,
      (report.result().mkString("\n") + "\n").getBytes(StandardCharsets.UTF_8))
    // scalastyle:off println
    println(s"option audit written to ${out.getAbsolutePath}")
    // scalastyle:on println
  }
}

