/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.catalyst.expressions.codegen.varka

import java.nio.file.Files

import scala.jdk.CollectionConverters._
import scala.util.Try

import com.fasterxml.jackson.databind.ObjectMapper

import org.apache.spark.SparkFunSuite
import org.apache.spark.sql.catalyst.expressions.{Alias, Attribute, AttributeReference, Expression, ExtractANSIIntervalMonths, InSet, NamedExpression}
import org.apache.spark.sql.catalyst.expressions.codegen.VarkaExpressionCompiler
import org.apache.spark.sql.types.{DateType, DayTimeIntervalType, IntegerType, LongType, TimeType, YearMonthIntervalType}
import org.apache.spark.util.Utils

/**
 * The expression coverage table in `docs/sql-varka.md`, generated and checked rather than
 * written by hand.
 *
 * The question a newcomer asks first is "does Varka cover the expression I care about", and
 * before this suite the only answer was to read a 1900-line Scala match. A table answers it,
 * but a hand-written table drifts: it can claim an expression the compiler declines, and it
 * can silently miss one the compiler gained. Both failures are checked here.
 *
 *  - Every documented row is resolved and put through the real compiler, and must fuse - a
 *    predicate row conjunct by conjunct, since a residual conjunct runs on the row engine. The
 *    table cannot claim support that does not exist.
 *  - Every Catalyst expression class the compiler matches on must appear in some documented
 *    row's resolved tree. The table cannot omit an expression the compiler admits, so adding
 *    an arm to the compiler without documenting it fails here.
 *  - The committed markdown must equal what this suite renders, so the file in the repository
 *    is the generated artifact and not a copy of it.
 *
 * The same rows are also written to `sql/varka/coverage.json`, which carries what the prose
 * table cannot: the Catalyst expression class behind each row. That file exists for readers
 * who arrive with a query rather than a question - "is this expression covered" is a grep in
 * it, and "which arm of the compiler serves this Catalyst class" is a lookup. It is checked
 * the same way and regenerated by the same command, so the two cannot disagree.
 *
 * Regenerate after adding a row with:
 * {{{
 *   VARKA_COVERAGE_REGEN=true build/sbt 'catalyst/testOnly *VarkaCoverageSuite'
 * }}}
 *
 * The same shape as Spark's own `SQLKeywordSuite`, which fails when the ANSI keyword
 * documentation and the parser grammar disagree.
 */
class VarkaCoverageSuite extends SparkFunSuite {

  // The columns every row is written against. They are the columns of the benchmark's
  // `varka_dates` table (`Surface.java`), so an expression in the table can be pasted into
  // the reproduction guide's queries unchanged.
  private val d = AttributeReference("d", DateType)()
  private val d2 = AttributeReference("d2", DateType)()
  private val i = AttributeReference("i", IntegerType)()
  private val ymm = AttributeReference("ymm",
    YearMonthIntervalType(YearMonthIntervalType.MONTH, YearMonthIntervalType.MONTH))()
  private val ymy = AttributeReference("ymy",
    YearMonthIntervalType(YearMonthIntervalType.YEAR, YearMonthIntervalType.YEAR))()
  private val ym = AttributeReference("ym",
    YearMonthIntervalType(YearMonthIntervalType.YEAR, YearMonthIntervalType.MONTH))()

  // The long lane's columns (task 29): `bigint`, `TIME(6)` and a day-time interval, two of
  // each so a comparison can be column against column as well as against a literal.
  private val l = AttributeReference("l", LongType)()
  private val l2 = AttributeReference("l2", LongType)()
  private val t = AttributeReference("t", TimeType(6))()
  private val t2 = AttributeReference("t2", TimeType(6))()
  private val dt = AttributeReference("dt", DayTimeIntervalType())()
  private val dt2 = AttributeReference("dt2", DayTimeIntervalType())()

  private val columns: Seq[Attribute] = Seq(d, d2, i, ymm, ymy, ym, l, l2, t, t2, dt, dt2)

  /**
   * One documented expression. `sql` is both what the table prints and what the check
   * compiles, except where `built` overrides it - the one case is `InSet`, which no SQL
   * spelling produces directly because Spark's optimizer, not its parser, creates it. Such a
   * row also gives `executable`, SQL that a query can run and that the optimizer turns into the
   * same expression, so that `VarkaCoverageDifferentialSuite` can run every row of the table.
   */
  private case class Row(
      sql: String,
      note: String = "",
      built: Option[Expression] = None,
      executable: Option[String] = None)

  private case class Family(title: String, predicates: Boolean, rows: Seq[Row])

  private val families: Seq[Family] = Seq(
    Family("Day arithmetic", predicates = false, Seq(
      Row("date_add(d, 3)"),
      Row("date_add(d, i)", "a column offset, under a per-batch bound on its range"),
      Row("date_sub(d, 5)"),
      Row("d + CAST(i AS INTERVAL DAY)", "the day-interval spelling of a column offset"),
      Row("datediff(d2, d)"),
      Row("unix_date(d)"),
      Row("date_from_unix_date(unix_date(d))"))),

    Family("Calendar fields", predicates = false, Seq(
      Row("year(d)"),
      Row("month(d)"),
      Row("day(d)"),
      Row("quarter(d)"),
      Row("dayofyear(d)"),
      Row("dayofweek(d)"),
      Row("weekday(d)"),
      Row("extract(DAYOFWEEK_ISO FROM d)"),
      Row("weekofyear(d)"),
      Row("extract(YEAROFWEEK FROM d)"),
      Row("last_day(d)"),
      Row("next_day(d, 'MONDAY')", "the day name must be a literal"),
      Row("make_date(2021, i, 1)"),
      Row("trunc(d, 'YEAR')"),
      Row("trunc(d, 'MONTH')"),
      Row("trunc(d, 'QUARTER')"),
      Row("trunc(d, 'WEEK')"))),

    Family("Months and year-month intervals", predicates = false, Seq(
      Row("add_months(d, 3)"),
      Row("add_months(d, i)"),
      Row("d + INTERVAL 3 MONTH"),
      Row("d + ym"),
      Row("d - ym"),
      Row("make_ym_interval(year(d), month(d))",
        "the operands must be bounded - over a bare int column the checked multiply inside "
          + "it keeps its overflow test and declines"),
      Row("make_ym_interval(year(d), month(d)) * 2",
        "a checked multiply, so bounded operands again: `ym * 2` over a stored interval "
          + "column declines"),
      Row("abs(ym)"),
      Row("ym - ymm"),
      Row("CAST(ymy AS INTERVAL MONTH)"),
      Row("extract(YEAR FROM ym)",
        "a division by twelve over a month count nothing bounds, so the calendar's "
          + "range-narrowed magic cannot serve it; a multiply-high through 64-bit lanes does"),
      Row("extract(YEAR FROM ym) - 1", "the quotient feeding further int arithmetic"))),

    Family("Integer arithmetic", predicates = false, Seq(
      Row("i + 1"),
      Row("i - 1"),
      Row("year(d) * 2",
        "a multiply is checked, and only bounded operands take the check off: `i * 2` over "
          + "a bare int column declines"),
      Row("-i"),
      Row("year(d) + i"))),

    Family("Choice and nulls", predicates = false, Seq(
      Row("if(d < d2, d, d2)"),
      Row("CASE WHEN d < d2 THEN d ELSE d2 END"),
      Row("coalesce(d, d2)"),
      Row("greatest(d, d2)"),
      Row("least(d, d2)"))),

    Family("Predicates", predicates = true, Seq(
      Row("d IS NULL"),
      Row("d IS NOT NULL"),
      Row("d = d2"),
      Row("d < d2"),
      Row("d <= d2"),
      Row("d > d2"),
      Row("d >= d2"),
      Row("year(d) = 2021"),
      Row("NOT (d = d2)"),
      Row("d IN (DATE '2021-01-01', DATE '2021-06-01')", "up to 16 literals"),
      Row("year(d) = 2021 AND i > 0",
        "every conjunct of an AND fuses or the predicate is not in this table; the int column "
          + "compares in the kernel rather than leaving a residual row filter (task 122)"),
      Row("i > 0", "a bare int column compares in the kernel (task 122)"),
      Row("i IS NOT NULL",
        "the same column's validity word, which the optimizer infers beside `i > 0`"),
      Row("i = 5"),
      Row("month(d) > i", "an int column against a fused int field"),
      Row("year(d) = 2021 OR month(d) = 3"),
      // Over `spark.sql.optimizer.inSetConversionThreshold` (10 by default) the optimizer
      // rewrites the list to an `InSet`, which fuses up to the compiler's own cap of 16.
      Row("d IN (11 to 16 date literals)",
        "an IN list this long arrives from the optimizer as an InSet and fuses the same way",
        Some(InSet(d, (1 to 11).map(v => v.asInstanceOf[Any]).toSet)),
        Some((1 to 11).map(m => f"DATE '2021-$m%02d-01'").mkString("d IN (", ", ", ")"))))),

    // The long lane (task 29): three types, comparisons only. Arithmetic over them is task
    // 104 (`bigint`), 102 (`TIME`) and 103 (intervals), and stays out of this table until then.
    Family("Long-lane predicates", predicates = true, Seq(
      Row("l > l2"),
      Row("l = l2"),
      Row("l >= 5000000000", "a bigint literal takes a slot in the long lane's own table"),
      Row("l IS NULL"),
      Row("l IS NOT NULL"),
      Row("t < t2"),
      Row("t = TIME'12:34:56.789'",
        "a TIME literal of another precision reaches the column through the widening cast, "
          + "which is the identity on nanoseconds"),
      Row("dt > dt2"),
      Row("dt < INTERVAL '0' SECOND"),
      Row("dt IS NOT NULL"))),

    Family("Long-lane choice", predicates = false, Seq(
      Row("greatest(l, l2)"),
      Row("least(l, 5000000000)"),
      Row("CASE WHEN l < l2 THEN l ELSE l2 END"),
      Row("if(l IS NULL, l2, l)"),
      Row("greatest(t, t2)"),
      Row("CASE WHEN dt > INTERVAL '0' SECOND THEN dt ELSE dt2 END"))),

    Family("Time arithmetic", predicates = false, Seq(
      Row("t - t2", "a day-time interval, the nanosecond difference divided by a thousand"),
      Row("time_diff('HOUR', t, t2)",
        "the unit is a literal; a column of units would need a kernel per distinct value"),
      Row("time_diff('microsecond', t2, t)", "units are read case-insensitively, as " +
        "DateTimeUtils reads them"),
      Row("time_trunc('MINUTE', t)"),
      Row("time_trunc('MILLISECOND', t2)"),
      Row("hour(t)", "an int computed in the 64-bit lane and narrowed at the kernel's store, " +
        "the one place a lane changes width until task 28; so the extract fuses as an output " +
        "and declines under another expression"),
      Row("minute(t2)"),
      Row("second(t)"),
      Row("time_to_millis(t)"),
      Row("time_to_micros(t2)"),
      Row("time_from_millis(time_to_millis(t2))", "the count is guarded to the day's worth of " +
        "its unit, where the multiply is exact; a count outside declines the batch and the row " +
        "engine raises Spark's error, as for t + dt - so the count here is one that is inside " +
        "the day by construction"),
      Row("time_from_micros(time_to_micros(t))"),
      Row("t + INTERVAL '0 00:00:00' DAY TO SECOND",
        "a zero interval on purpose: this fixture reaches both ends of the day, so any other " +
          "constant crosses midnight on some row, where Spark raises an error rather than a " +
          "value. The sum is still guarded to the day; the crossing case, and a column " +
          "interval, are VarkaTimeArithmeticSuite's")))
  )

  private def out(e: Expression): NamedExpression = Alias(e, "c")()

  /** The expression a row checks: its SQL resolved against `columns`, or its override. */
  private def expressionOf(row: Row): Expression =
    row.built.getOrElse(VarkaSqlResolve.resolve(
      org.apache.spark.sql.catalyst.parser.CatalystSqlParser.parseExpression(row.sql), columns))

  test("every documented expression compiles to a fused kernel") {
    val failures = families.flatMap { family =>
      family.rows.flatMap { row =>
        val expr = expressionOf(row)
        // The decline reason comes from the partial compile, which records one per entry. A
        // row that declines is a documentation bug, and the reason is what says which.
        val reason =
          if (family.predicates) {
            // Every conjunct has to fuse, not just one: the table documents the predicate as
            // written, and a residual conjunct runs in a row filter above the Varka node.
            VarkaExpressionCompiler.compilePredicate(expr, columns) match {
              case Some(p) if p.specs.forall(_.fused) => None
              case Some(p) => Some(p.specs.flatMap(_.decline).map(_.reason).mkString("; "))
              case None => Some("the predicate compiled to nothing")
            }
          } else {
            VarkaExpressionCompiler.compile(Seq(out(expr)), columns) match {
              case Some(_) => None
              case None =>
                val partial = VarkaExpressionCompiler.compilePartial(Seq(out(expr)), columns)
                Some(partial.map(_.declines.values.map(_.reason).mkString("; "))
                  .getOrElse("no entry fused"))
            }
          }
        reason.map(r => s"${family.title}: ${row.sql}  ->  $r")
      }
    }
    assert(failures.isEmpty,
      "documented as covered, but the compiler declines:\n  " + failures.mkString("\n  "))
  }

  test("an expression matched only to decline really does decline") {
    // The exemption above is the only way a class the compiler matches can stay out of the
    // table, so it has to be self-policing: an entry that starts fusing is coverage and belongs
    // in the table, and leaving it here would hide it from every reader of the generated docs.
    val stillDeclining = matchedOnlyToDecline.keys.toSeq.sorted.filter { name =>
      val expr = name match {
        case "ExtractANSIIntervalMonths" => ExtractANSIIntervalMonths(ym)
        case other => fail(s"no expression built for $other")
      }
      VarkaExpressionCompiler.compile(Seq(out(expr)), columns).isDefined
    }
    assert(stillDeclining.isEmpty,
      "listed as matched-only-to-decline, but it fuses now - move it into the table:\n  " +
        stillDeclining.mkString(", "))
  }

  test("a class named only in a comment is not read as an arm") {
    // The scan reads source text, so prose quoting a pattern would otherwise count as one.
    // `VarkaExpressionCompiler` carries exactly such a comment, explaining why the TIME
    // expressions are matched through the `StaticInvoke` their replacement is.
    val stripped = withoutComments(
      "// case Year(child) =>\n/* case Month(child) => */\ncase DayOfYear(child) =>\n")
    assert(!stripped.contains("case Year("), stripped)
    assert(!stripped.contains("case Month("), stripped)
    assert(stripped.contains("case DayOfYear(child) =>"), stripped)
    assert(!admittedByCompiler.contains("HoursOfTime"),
      "the compiler has no HoursOfTime arm - it matches the StaticInvoke its replacement is")
  }

  test("the table documents every expression the compiler admits") {
    val documented = families.flatMap(_.rows).flatMap { row =>
      expressionOf(row).collect { case e: Expression => e.getClass.getSimpleName }
    }.toSet
    val missing =
      (admittedByCompiler -- infrastructure -- matchedOnlyToDecline.keySet -- documented)
        .toSeq.sorted
    assert(missing.isEmpty,
      "VarkaExpressionCompiler matches on these, and no row in the coverage table exercises\n" +
        "them - add a row to VarkaCoverageSuite and regenerate the table:\n  " +
        missing.mkString(", "))
  }

  test("docs/sql-varka.md carries the generated coverage table") {
    val doc = getWorkspaceFilePath("docs", "sql-varka.md")
    val text = Files.readString(doc)
    val rendered = render()
    if (regen) {
      Files.writeString(doc, replaceBetween(text, rendered))
      logInfo(s"regenerated the coverage table in $doc")
    } else {
      val current = between(text)
      assert(current === rendered,
        "docs/sql-varka.md is not what this suite renders. Regenerate it with\n" +
          "  VARKA_COVERAGE_REGEN=true build/sbt 'catalyst/testOnly *VarkaCoverageSuite'")
    }
  }

  /**
   * Whether to rewrite the documentation instead of checking it.
   *
   * The environment variable is the short form and the one the documentation quotes: sbt forks
   * the test JVM, so a `-D` on the `build/sbt` command line reaches sbt and not the tests, and
   * the property form needs `set Test/javaOptions += ...` the way `dev/varka_nightly.sh`
   * passes the fuzzer its seed. Both are accepted.
   */
  private def regen: Boolean =
    sys.env.get("VARKA_COVERAGE_REGEN").contains("true") ||
      sys.props.get("varka.coverage.regen").contains("true")

  test("sql/varka/coverage.json carries the same rows in machine-readable form") {
    val file = getWorkspaceFilePath("sql", "varka", "coverage.json")
    val rendered = renderJson()
    if (regen) {
      Files.writeString(file, rendered)
      logInfo(s"regenerated $file")
    } else {
      assert(Files.readString(file) === rendered,
        "sql/varka/coverage.json is not what this suite renders. Regenerate it with\n" +
          "  VARKA_COVERAGE_REGEN=true build/sbt 'catalyst/testOnly *VarkaCoverageSuite'")
    }
  }

  // --- the compiler's own list ------------------------------------------------------------

  /**
   * The Catalyst expression classes the compiler matches on, read from its source because there
   * is no runtime list to ask: the arms are a `match`, not a registry. The arms live in
   * `VarkaExpressionCompiler` and the four families it chains, so all five files are read, each
   * in its own language: a family ported to Java matches in a `switch`, whose type patterns
   * (`case Add a`) and `instanceof` tests are what name its classes there.
   *
   * Every pattern naming a capitalised type is collected, then kept only if it names a real
   * class in `org.apache.spark.sql.catalyst.expressions`. That filter is what removes the IR
   * nodes, the data types and the local extractors without a hand-maintained exclusion list.
   *
   * Comments are stripped first. A comment that quotes a pattern - "an arm matching
   * `case HoursOfTime(child)` would never fire" - is prose about an arm the compiler does not
   * have, and counting it would both fail this check and publish the class in `coverage.json`
   * as one Varka admits.
   */
  private lazy val admittedByCompiler: Set[String] = {
    val scalaFiles = Seq("VarkaExpressionCompiler", "VarkaChronoCompiler",
      "VarkaTimeCompiler", "VarkaConditionCompiler")
    val javaFiles = Seq("VarkaIntervalCompiler")
    def read(language: String, name: String): String =
      withoutComments(Files.readString(
        getWorkspaceFilePath("sql", "catalyst", "src", "main", language,
          "org", "apache", "spark", "sql", "catalyst", "expressions", "codegen",
          s"$name.$language")))
    val scalaPatterns = Seq(
      """case\s+([A-Z]\w*)\s*\(""".r,
      """case\s+\w+\s*@\s*([A-Z]\w*)\s*\(""".r,
      """case\s+\w+\s*:\s*([A-Z]\w*)""".r,
      """_\s*:\s*([A-Z]\w*)""".r)
    val javaPatterns = Seq(
      """case\s+([A-Z]\w*)\s+\w+\s*(?:when\b|->)""".r,
      """instanceof\s+([A-Z]\w*)""".r)
    def scan(sources: Seq[String], patterns: Seq[scala.util.matching.Regex]): Seq[String] =
      patterns.flatMap(p => sources.flatMap(p.findAllMatchIn(_).map(_.group(1))))
    val names = (scan(scalaFiles.map(read("scala", _)), scalaPatterns) ++
      scan(javaFiles.map(read("java", _)), javaPatterns)).toSet
    assert(names.size > 40, s"the pattern scan found only ${names.size} names; has the " +
      "compiler been restructured? This check is worthless if it silently matches nothing.")
    names.filter { n =>
      Try(Utils.classForName(s"org.apache.spark.sql.catalyst.expressions.$n"))
        .map(classOf[Expression].isAssignableFrom).getOrElse(false)
    }
  }

  /**
   * Scala source with its block and line comments removed, so that a pattern scan reads code
   * and not prose about code. Newlines are kept, so nothing on a later line joins an earlier
   * one and forms a pattern neither of them wrote.
   */
  private def withoutComments(source: String): String =
    source
      .replaceAll("""(?s)/\*.*?\*/""", "")
      .replaceAll("""(?m)//.*$""", "")

  /**
   * Matched by the compiler but not expressions a reader writes: `Alias` wraps every
   * projection entry, `BoundReference` is what a column becomes once bound, `Literal` is a
   * constant inside another row, and `RuntimeReplaceable` is a trait the compiler unwraps.
   */
  private val infrastructure =
    Set("Alias", "BoundReference", "Literal", "RuntimeReplaceable")

  /**
   * Expressions the compiler matches only in order to decline them with a specific reason.
   *
   * <p>They are not coverage - nothing fuses, so a row in the table would be a false claim -
   * but a {@code case} exists for each so that the decline names the real blocker rather than
   * reading as "unsupported expression", which would send a reader looking in the wrong place.
   * The value is what blocks it. The test below keeps the list honest: anything here that
   * starts fusing fails, so this cannot become a place to park work that has since landed.
   */
  private val matchedOnlyToDecline = Map(
    "ExtractANSIIntervalMonths" ->
      "the result is a ByteType, and Varka has neither a byte lane nor an Arrow vector for one")

  // --- rendering --------------------------------------------------------------------------

  private val beginMark = "<!-- BEGIN generated coverage table -->"
  private val endMark = "<!-- END generated coverage table -->"

  /**
   * The width audit's census (`sql/varka/width_audit.json`, task 153), read for one column of
   * the table: whether C2 lowers every Vector API call of the row's kernel at 128-bit lanes -
   * the species a NEON-only aarch64 host runs at. The refusals it records are this x86 JVM's at
   * a forced 128-bit species; the aarch64 runner's own census refuses nothing there
   * (`PLAN_TASK_153.md` 6). Absent when the census has not been taken.
   */
  private lazy val widthAudit: Option[(String, Map[String, Seq[String]])] = {
    val file = getWorkspaceFilePath("sql", "varka", "width_audit.json").toFile
    if (!file.exists()) {
      None
    } else {
      val doc = new ObjectMapper().readTree(file)
      val host = doc.get("host").get("cpu").asText()
      val narrow = Option(doc.get("widths").get("128")).map { n =>
        n.fieldNames().asScala.map { sql =>
          sql -> n.get(sql).elements().asScala.map(_.asText()).toSeq
        }.toMap
      }.getOrElse(Map.empty[String, Seq[String]])
      Some(host -> narrow)
    }
  }

  /**
   * The column's cell for one row, from what C2 printed for the row's kernel at 128 bits. A
   * `not supported` line is a refusal, and it names its construction; the census file carries
   * those lines alone, since C2's other two kinds prove nothing about the final code and vary
   * between runs (`VarkaWidthAuditSuite.isRefusal`, task 154). The filter here is kept so a
   * census written before that change still renders the same column.
   */
  private def narrowVerdict(sql: String): String = widthAudit match {
    case None => "not audited"
    case Some((_, narrow)) => narrow.get(sql) match {
      case None => "not audited"
      case Some(lines) =>
        val refused = lines.filter(_.startsWith("not supported"))
        if (refused.isEmpty) "vector"
        else s"per-lane: ${refused.map(constructionOf).distinct.mkString(", ")}"
    }
  }

  /** The construction a `not supported` line is about, in words a reader of the table has. */
  private def constructionOf(line: String): String =
    if (line.contains("op=comp")) "compare to mask"
    else if (line.contains("op=blend")) "blend"
    else if (line.contains("op=cast")) "mask cast"
    else if (line.contains("op=broadcast") && line.contains("ismask=1")) "mask broadcast"
    else if (line.contains("op=test")) "mask test"
    else if (line.contains("is_masked_op=1")) "masked operation"
    else if (line.contains("ismask=1")) "mask logic"
    else if (line.contains("op=load") || line.contains("op=store")) "load or store"
    else "other"

  private def render(): String = {
    val sb = new StringBuilder
    widthAudit.foreach { case (host, _) =>
      sb.append("The *128-bit lanes* column is `sql/varka/width_audit.json`'s census on " +
        s"$host at a forced 128-bit species: `vector` means C2 refused no Vector API call in " +
        "the row's kernel there; `per-lane` names the constructions it had no lowering for, " +
        "which then run as Java loops over the lanes (task 153). It is this x86 JVM's table " +
        "below its own width: the pool's aarch64 runner, whose native species is 128 bits, " +
        "refuses nothing (`PLAN_TASK_153.md` 6).\n\n")
    }
    families.foreach { family =>
      sb.append(s"#### ${family.title}\n\n")
      sb.append(if (family.predicates) "| Predicate | Notes | 128-bit lanes |\n"
        else "| Expression | Notes | 128-bit lanes |\n")
      sb.append("|---|---|---|\n")
      family.rows.foreach(r =>
        sb.append(s"| `${r.sql}` | ${r.note} | ${narrowVerdict(r.sql)} |\n"))
      sb.append("\n")
    }
    sb.toString
  }

  /**
   * The same rows as JSON, through Jackson rather than string building so that a quote or a
   * backslash in a future row cannot produce a file that parses as something else.
   *
   * `LinkedHashMap` throughout: the output has to be byte-identical between runs or the check
   * above would fail on ordering alone.
   */
  private def renderJson(): String = {
    def ordered(pairs: (String, Any)*): java.util.LinkedHashMap[String, Any] = {
      val map = new java.util.LinkedHashMap[String, Any]()
      pairs.foreach { case (k, v) => map.put(k, v) }
      map
    }
    val rows = families.flatMap { family =>
      family.rows.map { row =>
        // The column references and the constants are in every row and identify nothing, so
        // the list carries only the classes that decide whether a row is covered.
        val classes = expressionOf(row)
          .collect { case e: Expression => e.getClass.getSimpleName }
          .filterNot(infrastructure.contains)
          .filterNot(_ == "AttributeReference")
        ordered(
          "sql" -> row.sql,
          "executable" -> row.executable.getOrElse(row.sql),
          "family" -> family.title,
          "form" -> (if (family.predicates) "predicate" else "projection"),
          "catalyst" -> classes.distinct.sorted.asJava,
          "note" -> row.note)
      }
    }
    val doc = ordered(
      "generated_by" -> ("VarkaCoverageSuite; regenerate with VARKA_COVERAGE_REGEN=true " +
        "build/sbt 'catalyst/testOnly *VarkaCoverageSuite'"),
      "description" -> ("Every expression the Varka compiler fuses, with the Catalyst " +
        "expression classes each one resolves to. Anything absent runs on Spark's row engine."),
      "columns" -> ordered(
        "d" -> "date", "d2" -> "date", "i" -> "int",
        "ymm" -> "interval month", "ymy" -> "interval year", "ym" -> "interval year to month",
        "l" -> "bigint", "l2" -> "bigint", "t" -> "time(6)", "t2" -> "time(6)",
        "dt" -> "interval day to second", "dt2" -> "interval day to second"),
      "expressions" -> rows.asJava,
      "catalyst_classes_admitted" -> (admittedByCompiler -- infrastructure).toSeq.sorted.asJava)
    new ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(doc) + "\n"
  }

  private def between(text: String): String = {
    val from = text.indexOf(beginMark)
    val to = text.indexOf(endMark)
    assert(from >= 0 && to > from, s"docs/sql-varka.md has no $beginMark ... $endMark block")
    text.substring(from + beginMark.length, to).stripPrefix("\n")
  }

  private def replaceBetween(text: String, body: String): String = {
    val from = text.indexOf(beginMark)
    val to = text.indexOf(endMark)
    text.substring(0, from + beginMark.length) + "\n" + body + text.substring(to)
  }
}
